#!/bin/bash

# Generated filename cleanup script
# Review carefully before running!

echo "Renaming: 11-16-EGY-1107.jpg → EGY-1107.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/11-16-EGY-1107.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/EGY-1107.jpg"
echo "Renaming: 11-16-EGY-1128.jpg → EGY-1128.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/11-16-EGY-1128.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/EGY-1128.jpg"
echo "Renaming: 11-17-EGY-172.jpg → EGY-172.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/11-17-EGY-172.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/EGY-172.jpg"
echo "Renaming: 11-17-EGY-550.jpg → EGY-550.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/11-17-EGY-550.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/EGY-550.jpg"
echo "Renaming: 11-17-EGY-598.jpg → EGY-598.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/11-17-EGY-598.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/EGY-598.jpg"
echo "Renaming: 11-18-EGY-110.jpg → EGY-110.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/11-18-EGY-110.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/EGY-110.jpg"
echo "Renaming: 11-21-EGY-262 2.jpg → EGY-262-2.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/11-21-EGY-262 2.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/EGY-262-2.jpg"
echo "Renaming: 11-28-EGY-508.jpg → EGY-508.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/11-28-EGY-508.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/EGY-508.jpg"
echo "Renaming: 11-28-EGY-512.jpg → EGY-512.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/11-28-EGY-512.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/EGY-512.jpg"
echo "Renaming: 12-01-EGY-150.jpg → EGY-150.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/12-01-EGY-150.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/EGY-150.jpg"
echo "Renaming: 12-14-EGY-342.jpg → EGY-342.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/12-14-EGY-342.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/EGY-342.jpg"
echo "Renaming: EGY-148 copy.jpg → EGY-148-copy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/EGY-148 copy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/EGY-148-copy.jpg"
echo "Renaming: EGY-53 copy.jpg → EGY-53-copy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/EGY-53 copy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/EGY-53-copy.jpg"
echo "Renaming: EGY-565 copy.jpg → EGY-565-copy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/EGY-565 copy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/EGY-565-copy.jpg"
echo "Renaming: EGY-61 copy.jpg → EGY-61-copy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/EGY-61 copy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/EGY-61-copy.jpg"
echo "Renaming: Sense of Scale.jpg → EGY-Sense-of-Scale.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/Sense of Scale.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/EGY-Sense-of-Scale.jpg"
echo "Renaming: Toiny Mernias Buoyancy1.jpg → EGY-Toiny-Mernias-Buoyancy1.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/Toiny Mernias Buoyancy1.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/EGY-Toiny-Mernias-Buoyancy1.jpg"
echo "Renaming: Tony Menias - Tuk Tuk Graveyard .jpg → EGY-Tony-Menias-Tuk-Tuk-Graveyard.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/Tony Menias - Tuk Tuk Graveyard .jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/EGY-Tony-Menias-Tuk-Tuk-Graveyard.jpg"
echo "Renaming: Tony Menias-Buoyancy.jpg → EGY-Tony-Menias-Buoyancy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/Tony Menias-Buoyancy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/EGY-Tony-Menias-Buoyancy.jpg"
echo "Renaming: IMG_1428.jpg → ETH-IMG_1428.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Ethiopia/IMG_1428.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Ethiopia/ETH-IMG_1428.jpg"
echo "Renaming: IMG_1615.jpg → ETH-IMG_1615.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Ethiopia/IMG_1615.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Ethiopia/ETH-IMG_1615.jpg"
echo "Renaming: IMG_1755.jpg → ETH-IMG_1755.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Ethiopia/IMG_1755.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Ethiopia/ETH-IMG_1755.jpg"
echo "Renaming: IMG_1852.jpg → ETH-IMG_1852.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Ethiopia/IMG_1852.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Ethiopia/ETH-IMG_1852.jpg"
echo "Renaming: IMG_1923.jpg → ETH-IMG_1923.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Ethiopia/IMG_1923.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Ethiopia/ETH-IMG_1923.jpg"
echo "Renaming: IMG_1930.jpg → ETH-IMG_1930.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Ethiopia/IMG_1930.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Ethiopia/ETH-IMG_1930.jpg"
echo "Renaming: IMG_2057.jpg → ETH-IMG_2057.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Ethiopia/IMG_2057.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Ethiopia/ETH-IMG_2057.jpg"
echo "Renaming: IMG_5169.jpg → MAR-IMG_5169.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Morocco/IMG_5169.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Morocco/MAR-IMG_5169.jpg"
echo "Renaming: IMG_5172.jpg → MAR-IMG_5172.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Morocco/IMG_5172.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Morocco/MAR-IMG_5172.jpg"
echo "Renaming: IMG_5206.jpg → MAR-IMG_5206.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Morocco/IMG_5206.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Morocco/MAR-IMG_5206.jpg"
echo "Renaming: IMG_5215.jpg → MAR-IMG_5215.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Morocco/IMG_5215.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Morocco/MAR-IMG_5215.jpg"
echo "Renaming: IMG_5249.jpg → MAR-IMG_5249.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Morocco/IMG_5249.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Morocco/MAR-IMG_5249.jpg"
echo "Renaming: Morocco-Hide n Seek.jpg → MAR-Morocco-Hide-n-Seek.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Morocco/Morocco-Hide n Seek.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Morocco/MAR-Morocco-Hide-n-Seek.jpg"
echo "Renaming: DSCF6215.jpg → DSCF6215.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/South Africa/DSCF6215.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/South Africa/DSCF6215.jpg"
echo "Renaming: DSCF6243.jpg → DSCF6243.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/South Africa/DSCF6243.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/South Africa/DSCF6243.jpg"
echo "Renaming: HK-5841 copy.jpg → HK-5841-copy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Hong Kong/HK-5841 copy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Hong Kong/HK-5841-copy.jpg"
echo "Renaming: HK-Pastel Playground 2-6570.jpg → HK-Pastel-Playground-2-6570.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Hong Kong/HK-Pastel Playground 2-6570.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Hong Kong/HK-Pastel-Playground-2-6570.jpg"
echo "Renaming: HK-Pastel Playground 3-6617.jpg → HK-Pastel-Playground-3-6617.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Hong Kong/HK-Pastel Playground 3-6617.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Hong Kong/HK-Pastel-Playground-3-6617.jpg"
echo "Renaming: HK-Pastel Playground 4-6559.jpg → HK-Pastel-Playground-4-6559.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Hong Kong/HK-Pastel Playground 4-6559.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Hong Kong/HK-Pastel-Playground-4-6559.jpg"
echo "Renaming: HK-Unexpected perspective-6919.jpg → HK-Unexpected-perspective-6919.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Hong Kong/HK-Unexpected perspective-6919.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Hong Kong/HK-Unexpected-perspective-6919.jpg"
echo "Renaming: Pastel Playground.jpg → Pastel-Playground.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Hong Kong/Pastel Playground.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Hong Kong/Pastel-Playground.jpg"
echo "Renaming: _DSF3449 copy.jpg → JAP-_DSF3449-copy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Japan/_DSF3449 copy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Japan/JAP-_DSF3449-copy.jpg"
echo "Renaming: Bridge to Enlightenment.jpg → MYA-Bridge-to-Enlightenment.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Myanmar/Bridge to Enlightenment.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Myanmar/MYA-Bridge-to-Enlightenment.jpg"
echo "Renaming: DSCF0098 copy.jpg → MYA-DSCF0098-copy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Myanmar/DSCF0098 copy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Myanmar/MYA-DSCF0098-copy.jpg"
echo "Renaming: DSCF0214 copy.jpg → MYA-DSCF0214-copy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Myanmar/DSCF0214 copy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Myanmar/MYA-DSCF0214-copy.jpg"
echo "Renaming: DSCF0467.jpg → MYA-DSCF0467.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Myanmar/DSCF0467.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Myanmar/MYA-DSCF0467.jpg"
echo "Renaming: DSCF0474.jpg → MYA-DSCF0474.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Myanmar/DSCF0474.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Myanmar/MYA-DSCF0474.jpg"
echo "Renaming: DSCF0506.jpg → MYA-DSCF0506.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Myanmar/DSCF0506.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Myanmar/MYA-DSCF0506.jpg"
echo "Renaming: DSCF0743.jpg → MYA-DSCF0743.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Myanmar/DSCF0743.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Myanmar/MYA-DSCF0743.jpg"
echo "Renaming: DSCF0817.jpg → MYA-DSCF0817.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Myanmar/DSCF0817.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Myanmar/MYA-DSCF0817.jpg"
echo "Renaming: DSCF1056.jpg → MYA-DSCF1056.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Myanmar/DSCF1056.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Myanmar/MYA-DSCF1056.jpg"
echo "Renaming: DSCF1206.jpg → MYA-DSCF1206.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Myanmar/DSCF1206.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Myanmar/MYA-DSCF1206.jpg"
echo "Renaming: DSCF9240.jpg → MYA-DSCF9240.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Myanmar/DSCF9240.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Myanmar/MYA-DSCF9240.jpg"
echo "Renaming: DSCF9634.jpg → MYA-DSCF9634.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Myanmar/DSCF9634.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Myanmar/MYA-DSCF9634.jpg"
echo "Renaming: DSCF9828.jpg → MYA-DSCF9828.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Myanmar/DSCF9828.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Myanmar/MYA-DSCF9828.jpg"
echo "Renaming: DSCF9886.jpg → MYA-DSCF9886.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Myanmar/DSCF9886.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Myanmar/MYA-DSCF9886.jpg"
echo "Renaming: DSCF9932.jpg → MYA-DSCF9932.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Myanmar/DSCF9932.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Myanmar/MYA-DSCF9932.jpg"
echo "Renaming: MYA-Morning Catch.jpg → MYA-Morning-Catch.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Myanmar/MYA-Morning Catch.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Myanmar/MYA-Morning-Catch.jpg"
echo "Renaming: Tony Menias-Fly.jpg → MYA-Tony-Menias-Fly.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Myanmar/Tony Menias-Fly.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Myanmar/MYA-Tony-Menias-Fly.jpg"
echo "Renaming: DSCF8230.jpg → NEP-DSCF8230.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Nepal/DSCF8230.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Nepal/NEP-DSCF8230.jpg"
echo "Renaming: DSCF8466.jpg → NEP-DSCF8466.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Nepal/DSCF8466.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Nepal/NEP-DSCF8466.jpg"
echo "Renaming: DSCF8726.jpg → NEP-DSCF8726.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Nepal/DSCF8726.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Nepal/NEP-DSCF8726.jpg"
echo "Renaming: NEP-Silent Stare.jpg → NEP-Silent-Stare.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Nepal/NEP-Silent Stare.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Nepal/NEP-Silent-Stare.jpg"
echo "Renaming: DSCF2520.jpg → THAI-DSCF2520.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Thailand/DSCF2520.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Thailand/THAI-DSCF2520.jpg"
echo "Renaming: DSCF3146.jpg → THAI-DSCF3146.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Thailand/DSCF3146.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Thailand/THAI-DSCF3146.jpg"
echo "Renaming: DSCF3152.jpg → THAI-DSCF3152.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Thailand/DSCF3152.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Thailand/THAI-DSCF3152.jpg"
echo "Renaming: DSCF3654.jpg → THAI-DSCF3654.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Thailand/DSCF3654.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Thailand/THAI-DSCF3654.jpg"
echo "Renaming: DSCF3700.jpg → THAI-DSCF3700.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Thailand/DSCF3700.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Thailand/THAI-DSCF3700.jpg"
echo "Renaming: DSCF3846.jpg → THAI-DSCF3846.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Thailand/DSCF3846.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Thailand/THAI-DSCF3846.jpg"
echo "Renaming: DSCF3890.jpg → THAI-DSCF3890.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Thailand/DSCF3890.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Thailand/THAI-DSCF3890.jpg"
echo "Renaming: DSCF4676.jpg → THAI-DSCF4676.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Thailand/DSCF4676.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Thailand/THAI-DSCF4676.jpg"
echo "Renaming: Simpler Times.jpg → THAI-Simpler-Times.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Thailand/Simpler Times.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Thailand/THAI-Simpler-Times.jpg"
echo "Renaming: _DSF4413 (1).jpg → THAI-_DSF4413-1.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Thailand/_DSF4413 (1).jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Thailand/THAI-_DSF4413-1.jpg"
echo "Renaming: DSCF8023.jpg → VIET-DSCF8023.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Vietnam/DSCF8023.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Vietnam/VIET-DSCF8023.jpg"
echo "Renaming: DSCF8045.jpg → VIET-DSCF8045.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Vietnam/DSCF8045.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Vietnam/VIET-DSCF8045.jpg"
echo "Renaming: DSCF8179.jpg → VIET-DSCF8179.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Vietnam/DSCF8179.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Vietnam/VIET-DSCF8179.jpg"
echo "Renaming: DSCF8205.jpg → VIET-DSCF8205.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Vietnam/DSCF8205.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Vietnam/VIET-DSCF8205.jpg"
echo "Renaming: DSCF8269.jpg → VIET-DSCF8269.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Vietnam/DSCF8269.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Vietnam/VIET-DSCF8269.jpg"
echo "Renaming: DSCF8333.jpg → VIET-DSCF8333.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Vietnam/DSCF8333.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Vietnam/VIET-DSCF8333.jpg"
echo "Renaming: DSCF8354.jpg → VIET-DSCF8354.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Vietnam/DSCF8354.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Vietnam/VIET-DSCF8354.jpg"
echo "Renaming: DSCF8577.jpg → VIET-DSCF8577.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Vietnam/DSCF8577.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Vietnam/VIET-DSCF8577.jpg"
echo "Renaming: DSCF8868.jpg → VIET-DSCF8868.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Vietnam/DSCF8868.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Vietnam/VIET-DSCF8868.jpg"
echo "Renaming: DSCF9016.jpg → VIET-DSCF9016.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Vietnam/DSCF9016.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Vietnam/VIET-DSCF9016.jpg"
echo "Renaming: DSCF9062.jpg → VIET-DSCF9062.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Vietnam/DSCF9062.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Vietnam/VIET-DSCF9062.jpg"
echo "Renaming: DSCF9211.jpg → VIET-DSCF9211.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Vietnam/DSCF9211.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Vietnam/VIET-DSCF9211.jpg"
echo "Renaming: Lazy Sunday.jpg → VIET-Lazy-Sunday.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Vietnam/Lazy Sunday.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Vietnam/VIET-Lazy-Sunday.jpg"
echo "Renaming: Vietnam Valley.jpg → Vietnam-Valley.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Vietnam/Vietnam Valley.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Vietnam/Vietnam-Valley.jpg"
echo "Renaming: DSCF1263.jpg → DSCF1263.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Central America & Caribbean/Cuba/DSCF1263.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Central America & Caribbean/Cuba/DSCF1263.jpg"
echo "Renaming: MEX-178 copy.jpg → MEX-178-copy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Central America & Caribbean/Mexico/MEX-178 copy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Central America & Caribbean/Mexico/MEX-178-copy.jpg"
echo "Renaming: MEX-56 copy.jpg → MEX-56-copy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Central America & Caribbean/Mexico/MEX-56 copy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Central America & Caribbean/Mexico/MEX-56-copy.jpg"
echo "Renaming: MEX-Miss Technicolor-8.jpg → MEX-Miss-Technicolor-8.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Central America & Caribbean/Mexico/MEX-Miss Technicolor-8.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Central America & Caribbean/Mexico/MEX-Miss-Technicolor-8.jpg"
echo "Renaming: 2019-02-05 10.22.37 pm.png → 2019-02-05-102237-pm.png"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Clients & Partners/2019-02-05 10.22.37 pm.png" "/home/camo/new/beloveful.com/public/Website beloveful.com/Clients & Partners/2019-02-05-102237-pm.png"
echo "Renaming: Time_Magazine_logo.svg.png → Time_Magazine_logosvg.png"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Clients & Partners/Time_Magazine_logo.svg.png" "/home/camo/new/beloveful.com/public/Website beloveful.com/Clients & Partners/Time_Magazine_logosvg.png"
echo "Renaming: pngegg (1).png → pngegg-1.png"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Clients & Partners/pngegg (1).png" "/home/camo/new/beloveful.com/public/Website beloveful.com/Clients & Partners/pngegg-1.png"
echo "Renaming: pngegg (2).png → pngegg-2.png"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Clients & Partners/pngegg (2).png" "/home/camo/new/beloveful.com/public/Website beloveful.com/Clients & Partners/pngegg-2.png"
echo "Renaming: DSCF3088 copy.jpg → DSCF3088-copy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Erasing Borders/DSCF3088 copy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Erasing Borders/DSCF3088-copy.jpg"
echo "Renaming: FRA-DSCF0103 copy.jpg → FRA-DSCF0103-copy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Erasing Borders/FRA-DSCF0103 copy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Erasing Borders/FRA-DSCF0103-copy.jpg"
echo "Renaming: Greece-DSCF3935 copy 3.jpg → GRC-Greece-DSCF3935-copy-3.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Erasing Borders/Greece-DSCF3935 copy 3.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Erasing Borders/GRC-Greece-DSCF3935-copy-3.jpg"
echo "Renaming: MOR-IMG_5248 copy.jpg → MOR-IMG_5248-copy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Erasing Borders/MOR-IMG_5248 copy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Erasing Borders/MOR-IMG_5248-copy.jpg"
echo "Renaming: MYA-DSCF0783 copy.jpg → MYA-DSCF0783-copy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Erasing Borders/MYA-DSCF0783 copy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Erasing Borders/MYA-DSCF0783-copy.jpg"
echo "Renaming: MYA-DSCF9634 copy.jpg → MYA-DSCF9634-copy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Erasing Borders/MYA-DSCF9634 copy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Erasing Borders/MYA-DSCF9634-copy.jpg"
echo "Renaming: NEP-DSCF8737 copy.jpg → NEP-DSCF8737-copy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Erasing Borders/NEP-DSCF8737 copy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Erasing Borders/NEP-DSCF8737-copy.jpg"
echo "Renaming: NEP-Silent Stare copy.jpg → NEP-Silent-Stare-copy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Erasing Borders/NEP-Silent Stare copy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Erasing Borders/NEP-Silent-Stare-copy.jpg"
echo "Renaming: NatureVSNurture copy.jpg → NatureVSNurture-copy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Erasing Borders/NatureVSNurture copy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Erasing Borders/NatureVSNurture-copy.jpg"
echo "Renaming: NyC-DSCF8922 copy 2.jpg → NyC-DSCF8922-copy-2.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Erasing Borders/NyC-DSCF8922 copy 2.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Erasing Borders/NyC-DSCF8922-copy-2.jpg"
echo "Renaming: PAL-DSCF3675 copy.jpg → PAL-DSCF3675-copy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Erasing Borders/PAL-DSCF3675 copy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Erasing Borders/PAL-DSCF3675-copy.jpg"
echo "Renaming: PHI-1662 copy.jpg → PHI-1662-copy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Erasing Borders/PHI-1662 copy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Erasing Borders/PHI-1662-copy.jpg"
echo "Renaming: THAI-DSCF3890 copy.jpg → THAI-DSCF3890-copy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Erasing Borders/THAI-DSCF3890 copy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Erasing Borders/THAI-DSCF3890-copy.jpg"
echo "Renaming: Tony Menias - Two Girls in Window.jpg → Tony-Menias-Two-Girls-in-Window.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Erasing Borders/Tony Menias - Two Girls in Window.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Erasing Borders/Tony-Menias-Two-Girls-in-Window.jpg"
echo "Renaming: Vietnam-DSCF8153 copy.jpg → Vietnam-DSCF8153-copy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Erasing Borders/Vietnam-DSCF8153 copy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Erasing Borders/Vietnam-DSCF8153-copy.jpg"
echo "Renaming: DSCF0063.jpg → FRA-DSCF0063.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/France/DSCF0063.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/France/FRA-DSCF0063.jpg"
echo "Renaming: DSCF0103.jpg → FRA-DSCF0103.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/France/DSCF0103.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/France/FRA-DSCF0103.jpg"
echo "Renaming: DSCF0106.jpg → FRA-DSCF0106.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/France/DSCF0106.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/France/FRA-DSCF0106.jpg"
echo "Renaming: DSCF0133.jpg → FRA-DSCF0133.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/France/DSCF0133.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/France/FRA-DSCF0133.jpg"
echo "Renaming: DSCF0271.jpg → FRA-DSCF0271.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/France/DSCF0271.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/France/FRA-DSCF0271.jpg"
echo "Renaming: DSCF0459.jpg → FRA-DSCF0459.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/France/DSCF0459.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/France/FRA-DSCF0459.jpg"
echo "Renaming: DSCF0509.jpg → FRA-DSCF0509.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/France/DSCF0509.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/France/FRA-DSCF0509.jpg"
echo "Renaming: DSCF0545.jpg → FRA-DSCF0545.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/France/DSCF0545.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/France/FRA-DSCF0545.jpg"
echo "Renaming: DSCF0654.jpg → FRA-DSCF0654.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/France/DSCF0654.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/France/FRA-DSCF0654.jpg"
echo "Renaming: DSCF0703.jpg → FRA-DSCF0703.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/France/DSCF0703.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/France/FRA-DSCF0703.jpg"
echo "Renaming: DSCF0739.jpg → FRA-DSCF0739.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/France/DSCF0739.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/France/FRA-DSCF0739.jpg"
echo "Renaming: DSCF0856.jpg → FRA-DSCF0856.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/France/DSCF0856.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/France/FRA-DSCF0856.jpg"
echo "Renaming: DSCF9603.jpg → FRA-DSCF9603.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/France/DSCF9603.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/France/FRA-DSCF9603.jpg"
echo "Renaming: DSCF9616.jpg → FRA-DSCF9616.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/France/DSCF9616.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/France/FRA-DSCF9616.jpg"
echo "Renaming: DSCF9661.jpg → FRA-DSCF9661.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/France/DSCF9661.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/France/FRA-DSCF9661.jpg"
echo "Renaming: DSCF9772.jpg → FRA-DSCF9772.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/France/DSCF9772.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/France/FRA-DSCF9772.jpg"
echo "Renaming: DSCF9790.jpg → FRA-DSCF9790.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/France/DSCF9790.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/France/FRA-DSCF9790.jpg"
echo "Renaming: DSCF9877.jpg → FRA-DSCF9877.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/France/DSCF9877.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/France/FRA-DSCF9877.jpg"
echo "Renaming: DSCF3407 copy.jpg → GRC-DSCF3407-copy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Greece/DSCF3407 copy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Greece/GRC-DSCF3407-copy.jpg"
echo "Renaming: DSCF3837.jpg → GRC-DSCF3837.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Greece/DSCF3837.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Greece/GRC-DSCF3837.jpg"
echo "Renaming: DSCF3935.jpg → GRC-DSCF3935.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Greece/DSCF3935.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Greece/GRC-DSCF3935.jpg"
echo "Renaming: DSCF3950.jpg → GRC-DSCF3950.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Greece/DSCF3950.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Greece/GRC-DSCF3950.jpg"
echo "Renaming: DSCF4025.jpg → GRC-DSCF4025.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Greece/DSCF4025.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Greece/GRC-DSCF4025.jpg"
echo "Renaming: DSCF4135.jpg → GRC-DSCF4135.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Greece/DSCF4135.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Greece/GRC-DSCF4135.jpg"
echo "Renaming: DSCF4185.jpg → GRC-DSCF4185.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Greece/DSCF4185.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Greece/GRC-DSCF4185.jpg"
echo "Renaming: DSCF4186.jpg → GRC-DSCF4186.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Greece/DSCF4186.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Greece/GRC-DSCF4186.jpg"
echo "Renaming: DSCF4324.jpg → GRC-DSCF4324.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Greece/DSCF4324.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Greece/GRC-DSCF4324.jpg"
echo "Renaming: DSCF4458.jpg → GRC-DSCF4458.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Greece/DSCF4458.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Greece/GRC-DSCF4458.jpg"
echo "Renaming: DSCF4522.jpg → GRC-DSCF4522.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Greece/DSCF4522.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Greece/GRC-DSCF4522.jpg"
echo "Renaming: DSCF4538.jpg → GRC-DSCF4538.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Greece/DSCF4538.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Greece/GRC-DSCF4538.jpg"
echo "Renaming: DSCF3805.jpg → ITA-DSCF3805.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Italy/DSCF3805.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Italy/ITA-DSCF3805.jpg"
echo "Renaming: DSCF3861.jpg → ITA-DSCF3861.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Italy/DSCF3861.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Italy/ITA-DSCF3861.jpg"
echo "Renaming: DSCF3885 copy 2.jpg → ITA-DSCF3885-copy-2.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Italy/DSCF3885 copy 2.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Italy/ITA-DSCF3885-copy-2.jpg"
echo "Renaming: DSCF3885 copy.jpg → ITA-DSCF3885-copy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Italy/DSCF3885 copy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Italy/ITA-DSCF3885-copy.jpg"
echo "Renaming: DSCF3885.jpg → ITA-DSCF3885.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Italy/DSCF3885.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Italy/ITA-DSCF3885.jpg"
echo "Renaming: DSCF3900.jpg → ITA-DSCF3900.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Italy/DSCF3900.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Italy/ITA-DSCF3900.jpg"
echo "Renaming: DSCF4018.jpg → ITA-DSCF4018.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Italy/DSCF4018.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Italy/ITA-DSCF4018.jpg"
echo "Renaming: DSCF4039.jpg → ITA-DSCF4039.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Italy/DSCF4039.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Italy/ITA-DSCF4039.jpg"
echo "Renaming: DSCF4511.jpg → ITA-DSCF4511.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Italy/DSCF4511.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Italy/ITA-DSCF4511.jpg"
echo "Renaming: DSCF4707.jpg → ITA-DSCF4707.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Italy/DSCF4707.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Italy/ITA-DSCF4707.jpg"
echo "Renaming: DSCF4927.jpg → ITA-DSCF4927.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Italy/DSCF4927.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Italy/ITA-DSCF4927.jpg"
echo "Renaming: DSCF5067.jpg → ITA-DSCF5067.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Italy/DSCF5067.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Italy/ITA-DSCF5067.jpg"
echo "Renaming: DSCF5156.jpg → ITA-DSCF5156.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Italy/DSCF5156.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Italy/ITA-DSCF5156.jpg"
echo "Renaming: DSCF5218.jpg → ITA-DSCF5218.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Italy/DSCF5218.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Italy/ITA-DSCF5218.jpg"
echo "Renaming: DSCF5223.jpg → ITA-DSCF5223.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Italy/DSCF5223.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Italy/ITA-DSCF5223.jpg"
echo "Renaming: DSCF5259.jpg → ITA-DSCF5259.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Italy/DSCF5259.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Italy/ITA-DSCF5259.jpg"
echo "Renaming: DSCF5985.jpg → ITA-DSCF5985.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Italy/DSCF5985.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Italy/ITA-DSCF5985.jpg"
echo "Renaming: DSCF5990.jpg → ITA-DSCF5990.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Italy/DSCF5990.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Italy/ITA-DSCF5990.jpg"
echo "Renaming: DSCF6139.jpg → ITA-DSCF6139.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Italy/DSCF6139.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Italy/ITA-DSCF6139.jpg"
echo "Renaming: DSCF6643.jpg → ITA-DSCF6643.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Italy/DSCF6643.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Italy/ITA-DSCF6643.jpg"
echo "Renaming: DSCF7366.jpg → ITA-DSCF7366.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Italy/DSCF7366.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Italy/ITA-DSCF7366.jpg"
echo "Renaming: DSCF7381.jpg → ITA-DSCF7381.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Italy/DSCF7381.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Italy/ITA-DSCF7381.jpg"
echo "Renaming: DSCF7678.jpg → ITA-DSCF7678.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Italy/DSCF7678.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Italy/ITA-DSCF7678.jpg"
echo "Renaming: DSCF7701.jpg → ITA-DSCF7701.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Italy/DSCF7701.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Italy/ITA-DSCF7701.jpg"
echo "Renaming: DSCF7793.jpg → ITA-DSCF7793.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Italy/DSCF7793.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Italy/ITA-DSCF7793.jpg"
echo "Renaming: ITA-6300 copy.jpg → ITA-6300-copy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Italy/ITA-6300 copy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Italy/ITA-6300-copy.jpg"
echo "Renaming: DSCF4995.jpg → SPA-DSCF4995.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Spain/DSCF4995.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Spain/SPA-DSCF4995.jpg"
echo "Renaming: DSCF0708.jpg → IRL-DSCF0708.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/UK & Ireland/DSCF0708.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/UK & Ireland/IRL-DSCF0708.jpg"
echo "Renaming: DSCF1055.jpg → IRL-DSCF1055.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/UK & Ireland/DSCF1055.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/UK & Ireland/IRL-DSCF1055.jpg"
echo "Renaming: DSCF2087.jpg → IRL-DSCF2087.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/UK & Ireland/DSCF2087.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/UK & Ireland/IRL-DSCF2087.jpg"
echo "Renaming: DSCF3031.jpg → IRL-DSCF3031.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/UK & Ireland/DSCF3031.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/UK & Ireland/IRL-DSCF3031.jpg"
echo "Renaming: DSCF3123.jpg → IRL-DSCF3123.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/UK & Ireland/DSCF3123.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/UK & Ireland/IRL-DSCF3123.jpg"
echo "Renaming: DSCF3251.jpg → IRL-DSCF3251.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/UK & Ireland/DSCF3251.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/UK & Ireland/IRL-DSCF3251.jpg"
echo "Renaming: Calm Before The Storm.jpg → Calm-Before-The-Storm.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Homepage/Desktop Landscape/Calm Before The Storm.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Homepage/Desktop Landscape/Calm-Before-The-Storm.jpg"
echo "Renaming: Headless Horseman-11-21-DSCF1337.jpg → Headless-Horseman-11-21-DSCF1337.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Homepage/Desktop Landscape/Headless Horseman-11-21-DSCF1337.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Homepage/Desktop Landscape/Headless-Horseman-11-21-DSCF1337.jpg"
echo "Renaming: Simpler Times.jpg → Simpler-Times.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Homepage/Desktop Landscape/Simpler Times.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Homepage/Desktop Landscape/Simpler-Times.jpg"
echo "Renaming: Snack Time.jpg → Snack-Time.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Homepage/Desktop Landscape/Snack Time.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Homepage/Desktop Landscape/Snack-Time.jpg"
echo "Renaming: Tony Menias-Fly.jpg → Tony-Menias-Fly.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Homepage/Desktop Landscape/Tony Menias-Fly.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Homepage/Desktop Landscape/Tony-Menias-Fly.jpg"
echo "Renaming: DSCF0103.jpg → DSCF0103.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Homepage/Mobile Portrait/DSCF0103.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Homepage/Mobile Portrait/DSCF0103.jpg"
echo "Renaming: DSCF8938.jpg → DSCF8938.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Homepage/Mobile Portrait/DSCF8938.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Homepage/Mobile Portrait/DSCF8938.jpg"
echo "Renaming: Into the Rabbit Hole.jpg → Into-the-Rabbit-Hole.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Homepage/Mobile Portrait/Into the Rabbit Hole.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Homepage/Mobile Portrait/Into-the-Rabbit-Hole.jpg"
echo "Renaming: Madame Jodhpur-03-19-DSCF7654.jpg → Madame-Jodhpur-03-19-DSCF7654.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Homepage/Mobile Portrait/Madame Jodhpur-03-19-DSCF7654.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Homepage/Mobile Portrait/Madame-Jodhpur-03-19-DSCF7654.jpg"
echo "Renaming: Pastel Playground.jpg → Pastel-Playground.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Homepage/Mobile Portrait/Pastel Playground.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Homepage/Mobile Portrait/Pastel-Playground.jpg"
echo "Renaming: Sense of Scale.jpg → Sense-of-Scale.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Homepage/Mobile Portrait/Sense of Scale.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Homepage/Mobile Portrait/Sense-of-Scale.jpg"
echo "Renaming: Beloveful black transparent.png → Beloveful-black-transparent.png"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Logo/Beloveful black transparent.png" "/home/camo/new/beloveful.com/public/Website beloveful.com/Logo/Beloveful-black-transparent.png"
echo "Renaming: Beloveful copy 2.png → Beloveful-copy-2.png"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Logo/Beloveful copy 2.png" "/home/camo/new/beloveful.com/public/Website beloveful.com/Logo/Beloveful-copy-2.png"
echo "Renaming: Beloveful copy 3.png → Beloveful-copy-3.png"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Logo/Beloveful copy 3.png" "/home/camo/new/beloveful.com/public/Website beloveful.com/Logo/Beloveful-copy-3.png"
echo "Renaming: Beloveful copy 6.png → Beloveful-copy-6.png"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Logo/Beloveful copy 6.png" "/home/camo/new/beloveful.com/public/Website beloveful.com/Logo/Beloveful-copy-6.png"
echo "Renaming: Beloveful copy.png → Beloveful-copy.png"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Logo/Beloveful copy.png" "/home/camo/new/beloveful.com/public/Website beloveful.com/Logo/Beloveful-copy.png"
echo "Renaming: IMG SMALl.jpg → IMG-SMALl.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Logo/IMG SMALl.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Logo/IMG-SMALl.jpg"
echo "Renaming: IMG_0007 copy.JPG → IMG_0007-copy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Logo/IMG_0007 copy.JPG" "/home/camo/new/beloveful.com/public/Website beloveful.com/Logo/IMG_0007-copy.jpg"
echo "Renaming: IMG_0007.JPG → IMG_0007.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Logo/IMG_0007.JPG" "/home/camo/new/beloveful.com/public/Website beloveful.com/Logo/IMG_0007.jpg"
echo "Renaming: IMG_1052.JPG → IMG_1052.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Logo/IMG_1052.JPG" "/home/camo/new/beloveful.com/public/Website beloveful.com/Logo/IMG_1052.jpg"
echo "Renaming: IMG_4610 copy.jpg copy 3.png → IMG_4610-copyjpg-copy-3.png"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Logo/IMG_4610 copy.jpg copy 3.png" "/home/camo/new/beloveful.com/public/Website beloveful.com/Logo/IMG_4610-copyjpg-copy-3.png"
echo "Renaming: IMG_4610.PNG → IMG_4610.png"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Logo/IMG_4610.PNG" "/home/camo/new/beloveful.com/public/Website beloveful.com/Logo/IMG_4610.png"
echo "Renaming: Beloveful white transparent.png → Beloveful-white-transparent.png"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Logo/White/Beloveful white transparent.png" "/home/camo/new/beloveful.com/public/Website beloveful.com/Logo/White/Beloveful-white-transparent.png"
echo "Renaming: Smaller 2.png → Smaller-2.png"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Logo/White/Smaller 2.png" "/home/camo/new/beloveful.com/public/Website beloveful.com/Logo/White/Smaller-2.png"
echo "Renaming: Smaller Logo.png → Smaller-Logo.png"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Logo/White/Smaller Logo.png" "/home/camo/new/beloveful.com/public/Website beloveful.com/Logo/White/Smaller-Logo.png"
echo "Renaming: beloveful logo inverted 75_ opacity.png → beloveful-logo-inverted-75_-opacity.png"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Logo/beloveful logo inverted 75_ opacity.png" "/home/camo/new/beloveful.com/public/Website beloveful.com/Logo/beloveful-logo-inverted-75_-opacity.png"
echo "Renaming: DSCF4385.jpg → JOR-DSCF4385.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Middle East/Jordan/DSCF4385.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Middle East/Jordan/JOR-DSCF4385.jpg"
echo "Renaming: DSCF4430.jpg → JOR-DSCF4430.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Middle East/Jordan/DSCF4430.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Middle East/Jordan/JOR-DSCF4430.jpg"
echo "Renaming: DSCF4488.jpg → JOR-DSCF4488.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Middle East/Jordan/DSCF4488.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Middle East/Jordan/JOR-DSCF4488.jpg"
echo "Renaming: DSCF4561.jpg → JOR-DSCF4561.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Middle East/Jordan/DSCF4561.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Middle East/Jordan/JOR-DSCF4561.jpg"
echo "Renaming: DSCF4619.jpg → JOR-DSCF4619.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Middle East/Jordan/DSCF4619.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Middle East/Jordan/JOR-DSCF4619.jpg"
echo "Renaming: DSCF4640.jpg → JOR-DSCF4640.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Middle East/Jordan/DSCF4640.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Middle East/Jordan/JOR-DSCF4640.jpg"
echo "Renaming: DSCF4694.jpg → JOR-DSCF4694.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Middle East/Jordan/DSCF4694.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Middle East/Jordan/JOR-DSCF4694.jpg"
echo "Renaming: CHI-3 copy.jpg → CHI-3-copy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/Chicago/CHI-3 copy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/Chicago/CHI-3-copy.jpg"
echo "Renaming: CHI-415 copy.jpg → CHI-415-copy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/Chicago/CHI-415 copy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/Chicago/CHI-415-copy.jpg"
echo "Renaming: CHI-7876 copy.jpg → CHI-7876-copy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/Chicago/CHI-7876 copy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/Chicago/CHI-7876-copy.jpg"
echo "Renaming: DSCF0396.jpg → CHI-DSCF0396.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/Chicago/DSCF0396.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/Chicago/CHI-DSCF0396.jpg"
echo "Renaming: DSCF0926.jpg → CHI-DSCF0926.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/Chicago/DSCF0926.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/Chicago/CHI-DSCF0926.jpg"
echo "Renaming: DSCF0942.jpg → CHI-DSCF0942.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/Chicago/DSCF0942.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/Chicago/CHI-DSCF0942.jpg"
echo "Renaming: DSCF1007.jpg → CHI-DSCF1007.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/Chicago/DSCF1007.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/Chicago/CHI-DSCF1007.jpg"
echo "Renaming: DSCF1196.jpg → CHI-DSCF1196.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/Chicago/DSCF1196.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/Chicago/CHI-DSCF1196.jpg"
echo "Renaming: DSCF1841.jpg → CHI-DSCF1841.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/Chicago/DSCF1841.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/Chicago/CHI-DSCF1841.jpg"
echo "Renaming: DSCF1980.jpg → CHI-DSCF1980.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/Chicago/DSCF1980.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/Chicago/CHI-DSCF1980.jpg"
echo "Renaming: DSCF2587.jpg → CHI-DSCF2587.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/Chicago/DSCF2587.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/Chicago/CHI-DSCF2587.jpg"
echo "Renaming: DSCF5972.jpg → CHI-DSCF5972.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/Chicago/DSCF5972.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/Chicago/CHI-DSCF5972.jpg"
echo "Renaming: DSCF7113.jpg → CHI-DSCF7113.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/Chicago/DSCF7113.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/Chicago/CHI-DSCF7113.jpg"
echo "Renaming: DSCF8938.jpg → CHI-DSCF8938.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/Chicago/DSCF8938.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/Chicago/CHI-DSCF8938.jpg"
echo "Renaming: DSCF9626.jpg → CHI-DSCF9626.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/Chicago/DSCF9626.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/Chicago/CHI-DSCF9626.jpg"
echo "Renaming: Fountain Fairy.jpg → CHI-Fountain-Fairy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/Chicago/Fountain Fairy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/Chicago/CHI-Fountain-Fairy.jpg"
echo "Renaming: Marina City-10-16-16.jpg → CHI-Marina-City-10-16-16.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/Chicago/Marina City-10-16-16.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/Chicago/CHI-Marina-City-10-16-16.jpg"
echo "Renaming: Tony Menias-Marathoners.jpg → CHI-Tony-Menias-Marathoners.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/Chicago/Tony Menias-Marathoners.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/Chicago/CHI-Tony-Menias-Marathoners.jpg"
echo "Renaming: Tony_Menias 1.jpg → CHI-Tony_Menias-1.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/Chicago/Tony_Menias 1.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/Chicago/CHI-Tony_Menias-1.jpg"
echo "Renaming: 08-09-NYC.jpg → NYC.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/New York/08-09-NYC.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/New York/NYC.jpg"
echo "Renaming: Btw the Lines.jpg → Btw-the-Lines.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/New York/Btw the Lines.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/New York/Btw-the-Lines.jpg"
echo "Renaming: DSCF1459.jpg → DSCF1459.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/New York/DSCF1459.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/New York/DSCF1459.jpg"
echo "Renaming: DSCF7931.jpg → DSCF7931.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/New York/DSCF7931.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/New York/DSCF7931.jpg"
echo "Renaming: DSCF8189.jpg → DSCF8189.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/New York/DSCF8189.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/New York/DSCF8189.jpg"
echo "Renaming: DSCF8922.jpg → DSCF8922.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/New York/DSCF8922.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/New York/DSCF8922.jpg"
echo "Renaming: Into the Rabbit Hole.jpg → Into-the-Rabbit-Hole.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/New York/Into the Rabbit Hole.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/New York/Into-the-Rabbit-Hole.jpg"
echo "Renaming: NYC-313 copy.jpg → NYC-313-copy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/New York/NYC-313 copy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/New York/NYC-313-copy.jpg"
echo "Renaming: Snack Time.jpg → Snack-Time.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/New York/Snack Time.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/New York/Snack-Time.jpg"
echo "Renaming: Stop Light.jpg → Stop-Light.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/New York/Stop Light.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/New York/Stop-Light.jpg"
echo "Renaming: 5x7s Life_s a Highway.jpg → 5x7s-Life_s-a-Highway.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/5x7s Life_s a Highway.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/5x7s-Life_s-a-Highway.jpg"
echo "Renaming: 5x7s-Family Meal.jpg → 5x7s-Family-Meal.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/5x7s-Family Meal.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/5x7s-Family-Meal.jpg"
echo "Renaming: 5x7s-Hide N Seek.jpg → 5x7s-Hide-N-Seek.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/5x7s-Hide N Seek.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/5x7s-Hide-N-Seek.jpg"
echo "Renaming: 5x7s-Into the Rabbit Hole.jpg → 5x7s-Into-the-Rabbit-Hole.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/5x7s-Into the Rabbit Hole.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/5x7s-Into-the-Rabbit-Hole.jpg"
echo "Renaming: 5x7s-Long Day.jpg → 5x7s-Long-Day.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/5x7s-Long Day.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/5x7s-Long-Day.jpg"
echo "Renaming: 5x7s-Mag Mile.jpg → 5x7s-Mag-Mile.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/5x7s-Mag Mile.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/5x7s-Mag-Mile.jpg"
echo "Renaming: 5x7s-Shapes & Shadows.jpg → 5x7s-Shapes-Shadows.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/5x7s-Shapes & Shadows.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/5x7s-Shapes-Shadows.jpg"
echo "Renaming: 5x7s-Ville de Lamour.jpg → 5x7s-Ville-de-Lamour.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/5x7s-Ville de Lamour.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/5x7s-Ville-de-Lamour.jpg"
echo "Renaming: Between The Lines 5x7.jpg → Between-The-Lines-5x7.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/Between The Lines 5x7.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/Between-The-Lines-5x7.jpg"
echo "Renaming: NY Slice 5x7.jpg → NY-Slice-5x7.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/NY Slice 5x7.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/NY-Slice-5x7.jpg"
echo "Renaming: Pressed 5x7.jpg → Pressed-5x7.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/Pressed 5x7.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/Pressed-5x7.jpg"
echo "Renaming: She Waited 5x7.jpg → She-Waited-5x7.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/She Waited 5x7.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/She-Waited-5x7.jpg"
echo "Renaming: Shy or Shame 5x7.jpg → Shy-or-Shame-5x7.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/Shy or Shame 5x7.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/Shy-or-Shame-5x7.jpg"
echo "Renaming: Sun Maiden 5x7.jpg → Sun-Maiden-5x7.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/Sun Maiden 5x7.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/Sun-Maiden-5x7.jpg"
echo "Renaming: Towel-Head 5x7.jpg → Towel-Head-5x7.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/Towel-Head 5x7.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/Towel-Head-5x7.jpg"
echo "Renaming: Violet Canine 5x7.jpg → Violet-Canine-5x7.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/Violet Canine 5x7.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/Violet-Canine-5x7.jpg"
echo "Renaming: snack time 5x7.jpg → snack-time-5x7.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/snack time 5x7.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/snack-time-5x7.jpg"
echo "Renaming: _DSF6993 copy.jpg → ARG-_DSF6993-copy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/South America/Argentina/_DSF6993 copy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/South America/Argentina/ARG-_DSF6993-copy.jpg"
echo "Renaming: Copy of CHI-0871.jpg → Copy-of-CHI-0871.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy of CHI-0871.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy-of-CHI-0871.jpg"
echo "Renaming: Copy of CHI-09-19-DSCF5133.jpg → Copy-of-CHI-09-19-DSCF5133.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy of CHI-09-19-DSCF5133.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy-of-CHI-09-19-DSCF5133.jpg"
echo "Renaming: Copy of CHI-2084-Website-2.jpg → Copy-of-CHI-2084-Website-2.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy of CHI-2084-Website-2.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy-of-CHI-2084-Website-2.jpg"
echo "Renaming: Copy of CHI-3.jpg → Copy-of-CHI-3.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy of CHI-3.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy-of-CHI-3.jpg"
echo "Renaming: Copy of CHI-359.jpg → Copy-of-CHI-359.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy of CHI-359.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy-of-CHI-359.jpg"
echo "Renaming: Copy of CHI-5041.jpg → Copy-of-CHI-5041.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy of CHI-5041.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy-of-CHI-5041.jpg"
echo "Renaming: Copy of CHI-5652.jpg → Copy-of-CHI-5652.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy of CHI-5652.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy-of-CHI-5652.jpg"
echo "Renaming: Copy of CHI-65.jpg → Copy-of-CHI-65.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy of CHI-65.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy-of-CHI-65.jpg"
echo "Renaming: Copy of CHI-8649.jpg → Copy-of-CHI-8649.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy of CHI-8649.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy-of-CHI-8649.jpg"
echo "Renaming: Copy of CHI-8789.jpg → Copy-of-CHI-8789.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy of CHI-8789.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy-of-CHI-8789.jpg"
echo "Renaming: Copy of CHI-9867.jpg → Copy-of-CHI-9867.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy of CHI-9867.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy-of-CHI-9867.jpg"
echo "Renaming: Copy of CHI-9872-Website-2.jpg → Copy-of-CHI-9872-Website-2.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy of CHI-9872-Website-2.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy-of-CHI-9872-Website-2.jpg"
echo "Renaming: Copy of CHI-Cafe-.jpg → Copy-of-CHI-Cafe.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy of CHI-Cafe-.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy-of-CHI-Cafe.jpg"
echo "Renaming: Copy of DSCF1980.jpg → Copy-of-DSCF1980.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy of DSCF1980.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy-of-DSCF1980.jpg"
echo "Renaming: Copy of DSCF8938.jpg → Copy-of-DSCF8938.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy of DSCF8938.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy-of-DSCF8938.jpg"
echo "Renaming: Copy of Fountain Fairy.jpg → Copy-of-Fountain-Fairy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy of Fountain Fairy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy-of-Fountain-Fairy.jpg"
echo "Renaming: Copy of Tony_Menias 1.jpg → Copy-of-Tony_Menias-1.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy of Tony_Menias 1.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy-of-Tony_Menias-1.jpg"
echo "Renaming: IMG_1306.jpg → IMG_1306.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/IMG_1306.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/IMG_1306.jpg"
echo "Renaming: IMG_20190825_155659.jpg → IMG_20190825_155659.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/IMG_20190825_155659.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/IMG_20190825_155659.jpg"
echo "Renaming: Time_Magazine_logo.svg.png → Time_Magazine_logosvg.png"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/clients/Time_Magazine_logo.svg.png" "/home/camo/new/beloveful.com/public/Website beloveful.com/clients/Time_Magazine_logosvg.png"
echo "Renaming: pngegg (1).png → pngegg-1.png"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/clients/pngegg (1).png" "/home/camo/new/beloveful.com/public/Website beloveful.com/clients/pngegg-1.png"
echo "Renaming: pngegg (2).png → pngegg-2.png"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/clients/pngegg (2).png" "/home/camo/new/beloveful.com/public/Website beloveful.com/clients/pngegg-2.png"
echo "Renaming: Copy of CHI-0871.jpg → Copy-of-CHI-0871.jpg"
mv "/home/camo/new/beloveful.com/public/workshop-photos/Copy of CHI-0871.jpg" "/home/camo/new/beloveful.com/public/workshop-photos/Copy-of-CHI-0871.jpg"
echo "Renaming: Copy of CHI-09-19-DSCF5133.jpg → Copy-of-CHI-09-19-DSCF5133.jpg"
mv "/home/camo/new/beloveful.com/public/workshop-photos/Copy of CHI-09-19-DSCF5133.jpg" "/home/camo/new/beloveful.com/public/workshop-photos/Copy-of-CHI-09-19-DSCF5133.jpg"
echo "Renaming: Copy of CHI-2084-Website-2.jpg → Copy-of-CHI-2084-Website-2.jpg"
mv "/home/camo/new/beloveful.com/public/workshop-photos/Copy of CHI-2084-Website-2.jpg" "/home/camo/new/beloveful.com/public/workshop-photos/Copy-of-CHI-2084-Website-2.jpg"
echo "Renaming: Copy of CHI-3.jpg → Copy-of-CHI-3.jpg"
mv "/home/camo/new/beloveful.com/public/workshop-photos/Copy of CHI-3.jpg" "/home/camo/new/beloveful.com/public/workshop-photos/Copy-of-CHI-3.jpg"
echo "Renaming: Copy of CHI-359.jpg → Copy-of-CHI-359.jpg"
mv "/home/camo/new/beloveful.com/public/workshop-photos/Copy of CHI-359.jpg" "/home/camo/new/beloveful.com/public/workshop-photos/Copy-of-CHI-359.jpg"
echo "Renaming: Copy of CHI-5041.jpg → Copy-of-CHI-5041.jpg"
mv "/home/camo/new/beloveful.com/public/workshop-photos/Copy of CHI-5041.jpg" "/home/camo/new/beloveful.com/public/workshop-photos/Copy-of-CHI-5041.jpg"
echo "Renaming: Copy of CHI-5652.jpg → Copy-of-CHI-5652.jpg"
mv "/home/camo/new/beloveful.com/public/workshop-photos/Copy of CHI-5652.jpg" "/home/camo/new/beloveful.com/public/workshop-photos/Copy-of-CHI-5652.jpg"
echo "Renaming: Copy of CHI-65.jpg → Copy-of-CHI-65.jpg"
mv "/home/camo/new/beloveful.com/public/workshop-photos/Copy of CHI-65.jpg" "/home/camo/new/beloveful.com/public/workshop-photos/Copy-of-CHI-65.jpg"
echo "Renaming: Copy of CHI-8649.jpg → Copy-of-CHI-8649.jpg"
mv "/home/camo/new/beloveful.com/public/workshop-photos/Copy of CHI-8649.jpg" "/home/camo/new/beloveful.com/public/workshop-photos/Copy-of-CHI-8649.jpg"
echo "Renaming: Copy of CHI-8789.jpg → Copy-of-CHI-8789.jpg"
mv "/home/camo/new/beloveful.com/public/workshop-photos/Copy of CHI-8789.jpg" "/home/camo/new/beloveful.com/public/workshop-photos/Copy-of-CHI-8789.jpg"
echo "Renaming: Copy of CHI-9867.jpg → Copy-of-CHI-9867.jpg"
mv "/home/camo/new/beloveful.com/public/workshop-photos/Copy of CHI-9867.jpg" "/home/camo/new/beloveful.com/public/workshop-photos/Copy-of-CHI-9867.jpg"
echo "Renaming: Copy of CHI-9872-Website-2.jpg → Copy-of-CHI-9872-Website-2.jpg"
mv "/home/camo/new/beloveful.com/public/workshop-photos/Copy of CHI-9872-Website-2.jpg" "/home/camo/new/beloveful.com/public/workshop-photos/Copy-of-CHI-9872-Website-2.jpg"
echo "Renaming: Copy of CHI-Cafe-.jpg → Copy-of-CHI-Cafe.jpg"
mv "/home/camo/new/beloveful.com/public/workshop-photos/Copy of CHI-Cafe-.jpg" "/home/camo/new/beloveful.com/public/workshop-photos/Copy-of-CHI-Cafe.jpg"
echo "Renaming: Copy of DSCF1980.jpg → Copy-of-DSCF1980.jpg"
mv "/home/camo/new/beloveful.com/public/workshop-photos/Copy of DSCF1980.jpg" "/home/camo/new/beloveful.com/public/workshop-photos/Copy-of-DSCF1980.jpg"
echo "Renaming: Copy of DSCF8938.jpg → Copy-of-DSCF8938.jpg"
mv "/home/camo/new/beloveful.com/public/workshop-photos/Copy of DSCF8938.jpg" "/home/camo/new/beloveful.com/public/workshop-photos/Copy-of-DSCF8938.jpg"
echo "Renaming: Copy of Fountain Fairy.jpg → Copy-of-Fountain-Fairy.jpg"
mv "/home/camo/new/beloveful.com/public/workshop-photos/Copy of Fountain Fairy.jpg" "/home/camo/new/beloveful.com/public/workshop-photos/Copy-of-Fountain-Fairy.jpg"
echo "Renaming: Copy of Tony_Menias 1.jpg → Copy-of-Tony_Menias-1.jpg"
mv "/home/camo/new/beloveful.com/public/workshop-photos/Copy of Tony_Menias 1.jpg" "/home/camo/new/beloveful.com/public/workshop-photos/Copy-of-Tony_Menias-1.jpg"
echo "Renaming: IMG_1306.jpg → IMG_1306.jpg"
mv "/home/camo/new/beloveful.com/public/workshop-photos/IMG_1306.jpg" "/home/camo/new/beloveful.com/public/workshop-photos/IMG_1306.jpg"
echo "Renaming: IMG_20190825_155659.jpg → IMG_20190825_155659.jpg"
mv "/home/camo/new/beloveful.com/public/workshop-photos/IMG_20190825_155659.jpg" "/home/camo/new/beloveful.com/public/workshop-photos/IMG_20190825_155659.jpg"
