#!/bin/bash

# Filename suggestions based on folder analysis
# Review carefully before running!

echo "Renaming: 11-16-EGY-1107.jpg → RSA-11-16-EGY-1107.jpg"
# mv "public/Website beloveful.com/Africa/Egypt/11-16-EGY-1107.jpg" "public/Website beloveful.com/Africa/Egypt/RSA-11-16-EGY-1107.jpg"
echo "Renaming: 11-16-EGY-1128.jpg → RSA-11-16-EGY-1128.jpg"
# mv "public/Website beloveful.com/Africa/Egypt/11-16-EGY-1128.jpg" "public/Website beloveful.com/Africa/Egypt/RSA-11-16-EGY-1128.jpg"
echo "Renaming: 11-17-EGY-172.jpg → RSA-11-17-EGY-172.jpg"
# mv "public/Website beloveful.com/Africa/Egypt/11-17-EGY-172.jpg" "public/Website beloveful.com/Africa/Egypt/RSA-11-17-EGY-172.jpg"
echo "Renaming: 11-17-EGY-550.jpg → RSA-11-17-EGY-550.jpg"
# mv "public/Website beloveful.com/Africa/Egypt/11-17-EGY-550.jpg" "public/Website beloveful.com/Africa/Egypt/RSA-11-17-EGY-550.jpg"
echo "Renaming: 11-17-EGY-598.jpg → RSA-11-17-EGY-598.jpg"
# mv "public/Website beloveful.com/Africa/Egypt/11-17-EGY-598.jpg" "public/Website beloveful.com/Africa/Egypt/RSA-11-17-EGY-598.jpg"
echo "Renaming: 11-18-EGY-110.jpg → RSA-11-18-EGY-110.jpg"
# mv "public/Website beloveful.com/Africa/Egypt/11-18-EGY-110.jpg" "public/Website beloveful.com/Africa/Egypt/RSA-11-18-EGY-110.jpg"
echo "Renaming: 11-21-EGY-262 2.jpg → RSA-11-21-EGY-262 2.jpg"
# mv "public/Website beloveful.com/Africa/Egypt/11-21-EGY-262 2.jpg" "public/Website beloveful.com/Africa/Egypt/RSA-11-21-EGY-262 2.jpg"
echo "Renaming: 11-28-EGY-508.jpg → RSA-11-28-EGY-508.jpg"
# mv "public/Website beloveful.com/Africa/Egypt/11-28-EGY-508.jpg" "public/Website beloveful.com/Africa/Egypt/RSA-11-28-EGY-508.jpg"
echo "Renaming: 11-28-EGY-512.jpg → RSA-11-28-EGY-512.jpg"
# mv "public/Website beloveful.com/Africa/Egypt/11-28-EGY-512.jpg" "public/Website beloveful.com/Africa/Egypt/RSA-11-28-EGY-512.jpg"
echo "Renaming: 12-01-EGY-150.jpg → RSA-12-01-EGY-150.jpg"
# mv "public/Website beloveful.com/Africa/Egypt/12-01-EGY-150.jpg" "public/Website beloveful.com/Africa/Egypt/RSA-12-01-EGY-150.jpg"
echo "Renaming: 12-14-EGY-342.jpg → RSA-12-14-EGY-342.jpg"
# mv "public/Website beloveful.com/Africa/Egypt/12-14-EGY-342.jpg" "public/Website beloveful.com/Africa/Egypt/RSA-12-14-EGY-342.jpg"
echo "Renaming: EGY1-1465.jpg → RSA-EGY1-1465.jpg"
# mv "public/Website beloveful.com/Africa/Egypt/EGY1-1465.jpg" "public/Website beloveful.com/Africa/Egypt/RSA-EGY1-1465.jpg"
echo "Renaming: EGY1-178.jpg → RSA-EGY1-178.jpg"
# mv "public/Website beloveful.com/Africa/Egypt/EGY1-178.jpg" "public/Website beloveful.com/Africa/Egypt/RSA-EGY1-178.jpg"
echo "Renaming: EGY45-.jpg → RSA-EGY45-.jpg"
# mv "public/Website beloveful.com/Africa/Egypt/EGY45-.jpg" "public/Website beloveful.com/Africa/Egypt/RSA-EGY45-.jpg"
echo "Renaming: Sense of Scale.jpg → RSA-Sense of Scale.jpg"
# mv "public/Website beloveful.com/Africa/Egypt/Sense of Scale.jpg" "public/Website beloveful.com/Africa/Egypt/RSA-Sense of Scale.jpg"
echo "Renaming: Toiny Mernias Buoyancy1.jpg → RSA-Toiny Mernias Buoyancy1.jpg"
# mv "public/Website beloveful.com/Africa/Egypt/Toiny Mernias Buoyancy1.jpg" "public/Website beloveful.com/Africa/Egypt/RSA-Toiny Mernias Buoyancy1.jpg"
echo "Renaming: Tony Menias - Tuk Tuk Graveyard .jpg → RSA-Tony Menias - Tuk Tuk Graveyard .jpg"
# mv "public/Website beloveful.com/Africa/Egypt/Tony Menias - Tuk Tuk Graveyard .jpg" "public/Website beloveful.com/Africa/Egypt/RSA-Tony Menias - Tuk Tuk Graveyard .jpg"
echo "Renaming: Tony Menias-Buoyancy.jpg → RSA-Tony Menias-Buoyancy.jpg"
# mv "public/Website beloveful.com/Africa/Egypt/Tony Menias-Buoyancy.jpg" "public/Website beloveful.com/Africa/Egypt/RSA-Tony Menias-Buoyancy.jpg"
echo "Renaming: IMG_1428.jpg → RSA-IMG_1428.jpg"
# mv "public/Website beloveful.com/Africa/Ethiopia/IMG_1428.jpg" "public/Website beloveful.com/Africa/Ethiopia/RSA-IMG_1428.jpg"
echo "Renaming: IMG_1615.jpg → RSA-IMG_1615.jpg"
# mv "public/Website beloveful.com/Africa/Ethiopia/IMG_1615.jpg" "public/Website beloveful.com/Africa/Ethiopia/RSA-IMG_1615.jpg"
echo "Renaming: IMG_1755.jpg → RSA-IMG_1755.jpg"
# mv "public/Website beloveful.com/Africa/Ethiopia/IMG_1755.jpg" "public/Website beloveful.com/Africa/Ethiopia/RSA-IMG_1755.jpg"
echo "Renaming: IMG_1852.jpg → RSA-IMG_1852.jpg"
# mv "public/Website beloveful.com/Africa/Ethiopia/IMG_1852.jpg" "public/Website beloveful.com/Africa/Ethiopia/RSA-IMG_1852.jpg"
echo "Renaming: IMG_1923.jpg → RSA-IMG_1923.jpg"
# mv "public/Website beloveful.com/Africa/Ethiopia/IMG_1923.jpg" "public/Website beloveful.com/Africa/Ethiopia/RSA-IMG_1923.jpg"
echo "Renaming: IMG_1930.jpg → RSA-IMG_1930.jpg"
# mv "public/Website beloveful.com/Africa/Ethiopia/IMG_1930.jpg" "public/Website beloveful.com/Africa/Ethiopia/RSA-IMG_1930.jpg"
echo "Renaming: IMG_2057.jpg → RSA-IMG_2057.jpg"
# mv "public/Website beloveful.com/Africa/Ethiopia/IMG_2057.jpg" "public/Website beloveful.com/Africa/Ethiopia/RSA-IMG_2057.jpg"
echo "Renaming: IMG_5169.jpg → RSA-IMG_5169.jpg"
# mv "public/Website beloveful.com/Africa/Morocco/IMG_5169.jpg" "public/Website beloveful.com/Africa/Morocco/RSA-IMG_5169.jpg"
echo "Renaming: IMG_5172.jpg → RSA-IMG_5172.jpg"
# mv "public/Website beloveful.com/Africa/Morocco/IMG_5172.jpg" "public/Website beloveful.com/Africa/Morocco/RSA-IMG_5172.jpg"
echo "Renaming: IMG_5206.jpg → RSA-IMG_5206.jpg"
# mv "public/Website beloveful.com/Africa/Morocco/IMG_5206.jpg" "public/Website beloveful.com/Africa/Morocco/RSA-IMG_5206.jpg"
echo "Renaming: IMG_5215.jpg → RSA-IMG_5215.jpg"
# mv "public/Website beloveful.com/Africa/Morocco/IMG_5215.jpg" "public/Website beloveful.com/Africa/Morocco/RSA-IMG_5215.jpg"
echo "Renaming: IMG_5249.jpg → RSA-IMG_5249.jpg"
# mv "public/Website beloveful.com/Africa/Morocco/IMG_5249.jpg" "public/Website beloveful.com/Africa/Morocco/RSA-IMG_5249.jpg"
echo "Renaming: IMG_5263-Website-2.jpg → RSA-IMG_5263-Website-2.jpg"
# mv "public/Website beloveful.com/Africa/Morocco/IMG_5263-Website-2.jpg" "public/Website beloveful.com/Africa/Morocco/RSA-IMG_5263-Website-2.jpg"
echo "Renaming: MOR-05-16-IMG_5205.jpg → RSA-MOR-05-16-IMG_5205.jpg"
# mv "public/Website beloveful.com/Africa/Morocco/MOR-05-16-IMG_5205.jpg" "public/Website beloveful.com/Africa/Morocco/RSA-MOR-05-16-IMG_5205.jpg"
echo "Renaming: MOR-5380-05-07-16.jpg → RSA-MOR-5380-05-07-16.jpg"
# mv "public/Website beloveful.com/Africa/Morocco/MOR-5380-05-07-16.jpg" "public/Website beloveful.com/Africa/Morocco/RSA-MOR-5380-05-07-16.jpg"
echo "Renaming: MOR-IMG_5277.jpg → RSA-MOR-IMG_5277.jpg"
# mv "public/Website beloveful.com/Africa/Morocco/MOR-IMG_5277.jpg" "public/Website beloveful.com/Africa/Morocco/RSA-MOR-IMG_5277.jpg"
echo "Renaming: Morocco-AlmostHome.jpg → RSA-Morocco-AlmostHome.jpg"
# mv "public/Website beloveful.com/Africa/Morocco/Morocco-AlmostHome.jpg" "public/Website beloveful.com/Africa/Morocco/RSA-Morocco-AlmostHome.jpg"
echo "Renaming: Morocco-Hide n Seek.jpg → RSA-Morocco-Hide n Seek.jpg"
# mv "public/Website beloveful.com/Africa/Morocco/Morocco-Hide n Seek.jpg" "public/Website beloveful.com/Africa/Morocco/RSA-Morocco-Hide n Seek.jpg"
echo "Renaming: DSCF6215.jpg → RSA-DSCF6215.jpg"
# mv "public/Website beloveful.com/Africa/South Africa/DSCF6215.jpg" "public/Website beloveful.com/Africa/South Africa/RSA-DSCF6215.jpg"
echo "Renaming: DSCF6243.jpg → RSA-DSCF6243.jpg"
# mv "public/Website beloveful.com/Africa/South Africa/DSCF6243.jpg" "public/Website beloveful.com/Africa/South Africa/RSA-DSCF6243.jpg"
echo "Renaming: SA-11-22-DSCF5758.jpg → RSA-SA-11-22-DSCF5758.jpg"
# mv "public/Website beloveful.com/Africa/South Africa/SA-11-22-DSCF5758.jpg" "public/Website beloveful.com/Africa/South Africa/RSA-SA-11-22-DSCF5758.jpg"
echo "Renaming: SA-11-22-DSCF5766.jpg → RSA-SA-11-22-DSCF5766.jpg"
# mv "public/Website beloveful.com/Africa/South Africa/SA-11-22-DSCF5766.jpg" "public/Website beloveful.com/Africa/South Africa/RSA-SA-11-22-DSCF5766.jpg"
echo "Renaming: SA-11-22-DSCF5770.jpg → RSA-SA-11-22-DSCF5770.jpg"
# mv "public/Website beloveful.com/Africa/South Africa/SA-11-22-DSCF5770.jpg" "public/Website beloveful.com/Africa/South Africa/RSA-SA-11-22-DSCF5770.jpg"
echo "Renaming: SA-11-22-DSCF5780.jpg → RSA-SA-11-22-DSCF5780.jpg"
# mv "public/Website beloveful.com/Africa/South Africa/SA-11-22-DSCF5780.jpg" "public/Website beloveful.com/Africa/South Africa/RSA-SA-11-22-DSCF5780.jpg"
echo "Renaming: SA-11-22-DSCF5838.jpg → RSA-SA-11-22-DSCF5838.jpg"
# mv "public/Website beloveful.com/Africa/South Africa/SA-11-22-DSCF5838.jpg" "public/Website beloveful.com/Africa/South Africa/RSA-SA-11-22-DSCF5838.jpg"
echo "Renaming: SA-11-22-DSCF5864.jpg → RSA-SA-11-22-DSCF5864.jpg"
# mv "public/Website beloveful.com/Africa/South Africa/SA-11-22-DSCF5864.jpg" "public/Website beloveful.com/Africa/South Africa/RSA-SA-11-22-DSCF5864.jpg"
echo "Renaming: SA-11-22-DSCF5894.jpg → RSA-SA-11-22-DSCF5894.jpg"
# mv "public/Website beloveful.com/Africa/South Africa/SA-11-22-DSCF5894.jpg" "public/Website beloveful.com/Africa/South Africa/RSA-SA-11-22-DSCF5894.jpg"
echo "Renaming: SA-11-22-DSCF5926.jpg → RSA-SA-11-22-DSCF5926.jpg"
# mv "public/Website beloveful.com/Africa/South Africa/SA-11-22-DSCF5926.jpg" "public/Website beloveful.com/Africa/South Africa/RSA-SA-11-22-DSCF5926.jpg"
echo "Renaming: SA-11-22-DSCF5932.jpg → RSA-SA-11-22-DSCF5932.jpg"
# mv "public/Website beloveful.com/Africa/South Africa/SA-11-22-DSCF5932.jpg" "public/Website beloveful.com/Africa/South Africa/RSA-SA-11-22-DSCF5932.jpg"
echo "Renaming: SA-11-22-DSCF6142.jpg → RSA-SA-11-22-DSCF6142.jpg"
# mv "public/Website beloveful.com/Africa/South Africa/SA-11-22-DSCF6142.jpg" "public/Website beloveful.com/Africa/South Africa/RSA-SA-11-22-DSCF6142.jpg"
echo "Renaming: SA-11-22-DSCF6201.jpg → RSA-SA-11-22-DSCF6201.jpg"
# mv "public/Website beloveful.com/Africa/South Africa/SA-11-22-DSCF6201.jpg" "public/Website beloveful.com/Africa/South Africa/RSA-SA-11-22-DSCF6201.jpg"
echo "Renaming: SA-11-22-DSCF6210.jpg → RSA-SA-11-22-DSCF6210.jpg"
# mv "public/Website beloveful.com/Africa/South Africa/SA-11-22-DSCF6210.jpg" "public/Website beloveful.com/Africa/South Africa/RSA-SA-11-22-DSCF6210.jpg"
echo "Renaming: SA-11-22-DSCF6237.jpg → RSA-SA-11-22-DSCF6237.jpg"
# mv "public/Website beloveful.com/Africa/South Africa/SA-11-22-DSCF6237.jpg" "public/Website beloveful.com/Africa/South Africa/RSA-SA-11-22-DSCF6237.jpg"
echo "Renaming: SA-11-22-DSCF6247.jpg → RSA-SA-11-22-DSCF6247.jpg"
# mv "public/Website beloveful.com/Africa/South Africa/SA-11-22-DSCF6247.jpg" "public/Website beloveful.com/Africa/South Africa/RSA-SA-11-22-DSCF6247.jpg"
echo "Renaming: Pastel Playground.jpg → HK-Pastel Playground.jpg"
# mv "public/Website beloveful.com/Asia/Hong Kong/Pastel Playground.jpg" "public/Website beloveful.com/Asia/Hong Kong/HK-Pastel Playground.jpg"
echo "Renaming: _DSF5646-2.jpg → HK-_DSF5646-2.jpg"
# mv "public/Website beloveful.com/Asia/Hong Kong/_DSF5646-2.jpg" "public/Website beloveful.com/Asia/Hong Kong/HK-_DSF5646-2.jpg"
echo "Renaming: _DSF6254.jpg → HK-_DSF6254.jpg"
# mv "public/Website beloveful.com/Asia/Hong Kong/_DSF6254.jpg" "public/Website beloveful.com/Asia/Hong Kong/HK-_DSF6254.jpg"
echo "Renaming: _DSF6743-2.jpg → HK-_DSF6743-2.jpg"
# mv "public/Website beloveful.com/Asia/Hong Kong/_DSF6743-2.jpg" "public/Website beloveful.com/Asia/Hong Kong/HK-_DSF6743-2.jpg"
echo "Renaming: _DSF6882.jpg → HK-_DSF6882.jpg"
# mv "public/Website beloveful.com/Asia/Hong Kong/_DSF6882.jpg" "public/Website beloveful.com/Asia/Hong Kong/HK-_DSF6882.jpg"
echo "Renaming: _DSF6933.jpg → HK-_DSF6933.jpg"
# mv "public/Website beloveful.com/Asia/Hong Kong/_DSF6933.jpg" "public/Website beloveful.com/Asia/Hong Kong/HK-_DSF6933.jpg"
echo "Renaming: WanderingPaths.jpg → JAP-WanderingPaths.jpg"
# mv "public/Website beloveful.com/Asia/Japan/WanderingPaths.jpg" "public/Website beloveful.com/Asia/Japan/JAP-WanderingPaths.jpg"
echo "Renaming: _DSF2956.jpg → JAP-_DSF2956.jpg"
# mv "public/Website beloveful.com/Asia/Japan/_DSF2956.jpg" "public/Website beloveful.com/Asia/Japan/JAP-_DSF2956.jpg"
echo "Renaming: _DSF3121.jpg → JAP-_DSF3121.jpg"
# mv "public/Website beloveful.com/Asia/Japan/_DSF3121.jpg" "public/Website beloveful.com/Asia/Japan/JAP-_DSF3121.jpg"
echo "Renaming: _DSF3449 copy.jpg → JAP-_DSF3449 copy.jpg"
# mv "public/Website beloveful.com/Asia/Japan/_DSF3449 copy.jpg" "public/Website beloveful.com/Asia/Japan/JAP-_DSF3449 copy.jpg"
echo "Renaming: Bridge to Enlightenment.jpg → MYA-Bridge to Enlightenment.jpg"
# mv "public/Website beloveful.com/Asia/Myanmar/Bridge to Enlightenment.jpg" "public/Website beloveful.com/Asia/Myanmar/MYA-Bridge to Enlightenment.jpg"
echo "Renaming: DSCF0086-2.jpg → MYA-DSCF0086-2.jpg"
# mv "public/Website beloveful.com/Asia/Myanmar/DSCF0086-2.jpg" "public/Website beloveful.com/Asia/Myanmar/MYA-DSCF0086-2.jpg"
echo "Renaming: DSCF0098 copy.jpg → MYA-DSCF0098 copy.jpg"
# mv "public/Website beloveful.com/Asia/Myanmar/DSCF0098 copy.jpg" "public/Website beloveful.com/Asia/Myanmar/MYA-DSCF0098 copy.jpg"
echo "Renaming: DSCF0214 copy.jpg → MYA-DSCF0214 copy.jpg"
# mv "public/Website beloveful.com/Asia/Myanmar/DSCF0214 copy.jpg" "public/Website beloveful.com/Asia/Myanmar/MYA-DSCF0214 copy.jpg"
echo "Renaming: DSCF0467.jpg → MYA-DSCF0467.jpg"
# mv "public/Website beloveful.com/Asia/Myanmar/DSCF0467.jpg" "public/Website beloveful.com/Asia/Myanmar/MYA-DSCF0467.jpg"
echo "Renaming: DSCF0474.jpg → MYA-DSCF0474.jpg"
# mv "public/Website beloveful.com/Asia/Myanmar/DSCF0474.jpg" "public/Website beloveful.com/Asia/Myanmar/MYA-DSCF0474.jpg"
echo "Renaming: DSCF0506.jpg → MYA-DSCF0506.jpg"
# mv "public/Website beloveful.com/Asia/Myanmar/DSCF0506.jpg" "public/Website beloveful.com/Asia/Myanmar/MYA-DSCF0506.jpg"
echo "Renaming: DSCF0743.jpg → MYA-DSCF0743.jpg"
# mv "public/Website beloveful.com/Asia/Myanmar/DSCF0743.jpg" "public/Website beloveful.com/Asia/Myanmar/MYA-DSCF0743.jpg"
echo "Renaming: DSCF0817.jpg → MYA-DSCF0817.jpg"
# mv "public/Website beloveful.com/Asia/Myanmar/DSCF0817.jpg" "public/Website beloveful.com/Asia/Myanmar/MYA-DSCF0817.jpg"
echo "Renaming: DSCF0839-Website-2.jpg → MYA-DSCF0839-Website-2.jpg"
# mv "public/Website beloveful.com/Asia/Myanmar/DSCF0839-Website-2.jpg" "public/Website beloveful.com/Asia/Myanmar/MYA-DSCF0839-Website-2.jpg"
echo "Renaming: DSCF1006-2.jpg → MYA-DSCF1006-2.jpg"
# mv "public/Website beloveful.com/Asia/Myanmar/DSCF1006-2.jpg" "public/Website beloveful.com/Asia/Myanmar/MYA-DSCF1006-2.jpg"
echo "Renaming: DSCF1056.jpg → MYA-DSCF1056.jpg"
# mv "public/Website beloveful.com/Asia/Myanmar/DSCF1056.jpg" "public/Website beloveful.com/Asia/Myanmar/MYA-DSCF1056.jpg"
echo "Renaming: DSCF1206.jpg → MYA-DSCF1206.jpg"
# mv "public/Website beloveful.com/Asia/Myanmar/DSCF1206.jpg" "public/Website beloveful.com/Asia/Myanmar/MYA-DSCF1206.jpg"
echo "Renaming: DSCF9240.jpg → MYA-DSCF9240.jpg"
# mv "public/Website beloveful.com/Asia/Myanmar/DSCF9240.jpg" "public/Website beloveful.com/Asia/Myanmar/MYA-DSCF9240.jpg"
echo "Renaming: DSCF9634.jpg → MYA-DSCF9634.jpg"
# mv "public/Website beloveful.com/Asia/Myanmar/DSCF9634.jpg" "public/Website beloveful.com/Asia/Myanmar/MYA-DSCF9634.jpg"
echo "Renaming: DSCF9828.jpg → MYA-DSCF9828.jpg"
# mv "public/Website beloveful.com/Asia/Myanmar/DSCF9828.jpg" "public/Website beloveful.com/Asia/Myanmar/MYA-DSCF9828.jpg"
echo "Renaming: DSCF9886.jpg → MYA-DSCF9886.jpg"
# mv "public/Website beloveful.com/Asia/Myanmar/DSCF9886.jpg" "public/Website beloveful.com/Asia/Myanmar/MYA-DSCF9886.jpg"
echo "Renaming: DSCF9932.jpg → MYA-DSCF9932.jpg"
# mv "public/Website beloveful.com/Asia/Myanmar/DSCF9932.jpg" "public/Website beloveful.com/Asia/Myanmar/MYA-DSCF9932.jpg"
echo "Renaming: Enlightened.jpg → MYA-Enlightened.jpg"
# mv "public/Website beloveful.com/Asia/Myanmar/Enlightened.jpg" "public/Website beloveful.com/Asia/Myanmar/MYA-Enlightened.jpg"
echo "Renaming: Serendipity.jpg → MYA-Serendipity.jpg"
# mv "public/Website beloveful.com/Asia/Myanmar/Serendipity.jpg" "public/Website beloveful.com/Asia/Myanmar/MYA-Serendipity.jpg"
echo "Renaming: Tony Menias-Fly.jpg → MYA-Tony Menias-Fly.jpg"
# mv "public/Website beloveful.com/Asia/Myanmar/Tony Menias-Fly.jpg" "public/Website beloveful.com/Asia/Myanmar/MYA-Tony Menias-Fly.jpg"
echo "Renaming: DSCF8230.jpg → NPL-DSCF8230.jpg"
# mv "public/Website beloveful.com/Asia/Nepal/DSCF8230.jpg" "public/Website beloveful.com/Asia/Nepal/NPL-DSCF8230.jpg"
echo "Renaming: DSCF8466.jpg → NPL-DSCF8466.jpg"
# mv "public/Website beloveful.com/Asia/Nepal/DSCF8466.jpg" "public/Website beloveful.com/Asia/Nepal/NPL-DSCF8466.jpg"
echo "Renaming: DSCF8726.jpg → NPL-DSCF8726.jpg"
# mv "public/Website beloveful.com/Asia/Nepal/DSCF8726.jpg" "public/Website beloveful.com/Asia/Nepal/NPL-DSCF8726.jpg"
echo "Renaming: DSCF2498-Website-2.jpg → THA-DSCF2498-Website-2.jpg"
# mv "public/Website beloveful.com/Asia/Thailand/DSCF2498-Website-2.jpg" "public/Website beloveful.com/Asia/Thailand/THA-DSCF2498-Website-2.jpg"
echo "Renaming: DSCF2520.jpg → THA-DSCF2520.jpg"
# mv "public/Website beloveful.com/Asia/Thailand/DSCF2520.jpg" "public/Website beloveful.com/Asia/Thailand/THA-DSCF2520.jpg"
echo "Renaming: DSCF3146.jpg → THA-DSCF3146.jpg"
# mv "public/Website beloveful.com/Asia/Thailand/DSCF3146.jpg" "public/Website beloveful.com/Asia/Thailand/THA-DSCF3146.jpg"
echo "Renaming: DSCF3152.jpg → THA-DSCF3152.jpg"
# mv "public/Website beloveful.com/Asia/Thailand/DSCF3152.jpg" "public/Website beloveful.com/Asia/Thailand/THA-DSCF3152.jpg"
echo "Renaming: DSCF3654.jpg → THA-DSCF3654.jpg"
# mv "public/Website beloveful.com/Asia/Thailand/DSCF3654.jpg" "public/Website beloveful.com/Asia/Thailand/THA-DSCF3654.jpg"
echo "Renaming: DSCF3700.jpg → THA-DSCF3700.jpg"
# mv "public/Website beloveful.com/Asia/Thailand/DSCF3700.jpg" "public/Website beloveful.com/Asia/Thailand/THA-DSCF3700.jpg"
echo "Renaming: DSCF3846.jpg → THA-DSCF3846.jpg"
# mv "public/Website beloveful.com/Asia/Thailand/DSCF3846.jpg" "public/Website beloveful.com/Asia/Thailand/THA-DSCF3846.jpg"
echo "Renaming: DSCF3890.jpg → THA-DSCF3890.jpg"
# mv "public/Website beloveful.com/Asia/Thailand/DSCF3890.jpg" "public/Website beloveful.com/Asia/Thailand/THA-DSCF3890.jpg"
echo "Renaming: DSCF4676.jpg → THA-DSCF4676.jpg"
# mv "public/Website beloveful.com/Asia/Thailand/DSCF4676.jpg" "public/Website beloveful.com/Asia/Thailand/THA-DSCF4676.jpg"
echo "Renaming: Simpler Times.jpg → THA-Simpler Times.jpg"
# mv "public/Website beloveful.com/Asia/Thailand/Simpler Times.jpg" "public/Website beloveful.com/Asia/Thailand/THA-Simpler Times.jpg"
echo "Renaming: _DSF4410.jpg → THA-_DSF4410.jpg"
# mv "public/Website beloveful.com/Asia/Thailand/_DSF4410.jpg" "public/Website beloveful.com/Asia/Thailand/THA-_DSF4410.jpg"
echo "Renaming: _DSF4413 (1).jpg → THA-_DSF4413 (1).jpg"
# mv "public/Website beloveful.com/Asia/Thailand/_DSF4413 (1).jpg" "public/Website beloveful.com/Asia/Thailand/THA-_DSF4413 (1).jpg"
echo "Renaming: _DSF4413.jpg → THA-_DSF4413.jpg"
# mv "public/Website beloveful.com/Asia/Thailand/_DSF4413.jpg" "public/Website beloveful.com/Asia/Thailand/THA-_DSF4413.jpg"
echo "Renaming: _DSF4670.jpg → THA-_DSF4670.jpg"
# mv "public/Website beloveful.com/Asia/Thailand/_DSF4670.jpg" "public/Website beloveful.com/Asia/Thailand/THA-_DSF4670.jpg"
echo "Renaming: _DSF4784.jpg → THA-_DSF4784.jpg"
# mv "public/Website beloveful.com/Asia/Thailand/_DSF4784.jpg" "public/Website beloveful.com/Asia/Thailand/THA-_DSF4784.jpg"
echo "Renaming: _DSF4863.jpg → THA-_DSF4863.jpg"
# mv "public/Website beloveful.com/Asia/Thailand/_DSF4863.jpg" "public/Website beloveful.com/Asia/Thailand/THA-_DSF4863.jpg"
echo "Renaming: _DSF4899.jpg → THA-_DSF4899.jpg"
# mv "public/Website beloveful.com/Asia/Thailand/_DSF4899.jpg" "public/Website beloveful.com/Asia/Thailand/THA-_DSF4899.jpg"
echo "Renaming: _DSF5070.jpg → THA-_DSF5070.jpg"
# mv "public/Website beloveful.com/Asia/Thailand/_DSF5070.jpg" "public/Website beloveful.com/Asia/Thailand/THA-_DSF5070.jpg"
echo "Renaming: DSCF8023.jpg → VIE-DSCF8023.jpg"
# mv "public/Website beloveful.com/Asia/Vietnam/DSCF8023.jpg" "public/Website beloveful.com/Asia/Vietnam/VIE-DSCF8023.jpg"
echo "Renaming: DSCF8045.jpg → VIE-DSCF8045.jpg"
# mv "public/Website beloveful.com/Asia/Vietnam/DSCF8045.jpg" "public/Website beloveful.com/Asia/Vietnam/VIE-DSCF8045.jpg"
echo "Renaming: DSCF8179.jpg → VIE-DSCF8179.jpg"
# mv "public/Website beloveful.com/Asia/Vietnam/DSCF8179.jpg" "public/Website beloveful.com/Asia/Vietnam/VIE-DSCF8179.jpg"
echo "Renaming: DSCF8181-2.jpg → VIE-DSCF8181-2.jpg"
# mv "public/Website beloveful.com/Asia/Vietnam/DSCF8181-2.jpg" "public/Website beloveful.com/Asia/Vietnam/VIE-DSCF8181-2.jpg"
echo "Renaming: DSCF8205.jpg → VIE-DSCF8205.jpg"
# mv "public/Website beloveful.com/Asia/Vietnam/DSCF8205.jpg" "public/Website beloveful.com/Asia/Vietnam/VIE-DSCF8205.jpg"
echo "Renaming: DSCF8269.jpg → VIE-DSCF8269.jpg"
# mv "public/Website beloveful.com/Asia/Vietnam/DSCF8269.jpg" "public/Website beloveful.com/Asia/Vietnam/VIE-DSCF8269.jpg"
echo "Renaming: DSCF8333.jpg → VIE-DSCF8333.jpg"
# mv "public/Website beloveful.com/Asia/Vietnam/DSCF8333.jpg" "public/Website beloveful.com/Asia/Vietnam/VIE-DSCF8333.jpg"
echo "Renaming: DSCF8354.jpg → VIE-DSCF8354.jpg"
# mv "public/Website beloveful.com/Asia/Vietnam/DSCF8354.jpg" "public/Website beloveful.com/Asia/Vietnam/VIE-DSCF8354.jpg"
echo "Renaming: DSCF8577.jpg → VIE-DSCF8577.jpg"
# mv "public/Website beloveful.com/Asia/Vietnam/DSCF8577.jpg" "public/Website beloveful.com/Asia/Vietnam/VIE-DSCF8577.jpg"
echo "Renaming: DSCF8868.jpg → VIE-DSCF8868.jpg"
# mv "public/Website beloveful.com/Asia/Vietnam/DSCF8868.jpg" "public/Website beloveful.com/Asia/Vietnam/VIE-DSCF8868.jpg"
echo "Renaming: DSCF9016.jpg → VIE-DSCF9016.jpg"
# mv "public/Website beloveful.com/Asia/Vietnam/DSCF9016.jpg" "public/Website beloveful.com/Asia/Vietnam/VIE-DSCF9016.jpg"
echo "Renaming: DSCF9062.jpg → VIE-DSCF9062.jpg"
# mv "public/Website beloveful.com/Asia/Vietnam/DSCF9062.jpg" "public/Website beloveful.com/Asia/Vietnam/VIE-DSCF9062.jpg"
echo "Renaming: DSCF9211.jpg → VIE-DSCF9211.jpg"
# mv "public/Website beloveful.com/Asia/Vietnam/DSCF9211.jpg" "public/Website beloveful.com/Asia/Vietnam/VIE-DSCF9211.jpg"
echo "Renaming: FamilyMeal.jpg → VIE-FamilyMeal.jpg"
# mv "public/Website beloveful.com/Asia/Vietnam/FamilyMeal.jpg" "public/Website beloveful.com/Asia/Vietnam/VIE-FamilyMeal.jpg"
echo "Renaming: Lazy Sunday.jpg → VIE-Lazy Sunday.jpg"
# mv "public/Website beloveful.com/Asia/Vietnam/Lazy Sunday.jpg" "public/Website beloveful.com/Asia/Vietnam/VIE-Lazy Sunday.jpg"
echo "Renaming: TonyMenias-GirlsInWindow.jpg → VIE-TonyMenias-GirlsInWindow.jpg"
# mv "public/Website beloveful.com/Asia/Vietnam/TonyMenias-GirlsInWindow.jpg" "public/Website beloveful.com/Asia/Vietnam/VIE-TonyMenias-GirlsInWindow.jpg"
echo "Renaming: untitled-8559.jpg → VIE-untitled-8559.jpg"
# mv "public/Website beloveful.com/Asia/Vietnam/untitled-8559.jpg" "public/Website beloveful.com/Asia/Vietnam/VIE-untitled-8559.jpg"
echo "Renaming: breaks-chicago.jpg → CHI-breaks-chicago.jpg"
# mv "public/Website beloveful.com/Clients & Partners/breaks-chicago.jpg" "public/Website beloveful.com/Clients & Partners/CHI-breaks-chicago.jpg"
echo "Renaming: kissclipart-navy-pier-logo-clipart-chicago-shakespeare-theater-e550ac399dac0a24.jpg → CHI-kissclipart-navy-pier-logo-clipart-chicago-shakespeare-theater-e550ac399dac0a24.jpg"
# mv "public/Website beloveful.com/Clients & Partners/kissclipart-navy-pier-logo-clipart-chicago-shakespeare-theater-e550ac399dac0a24.jpg" "public/Website beloveful.com/Clients & Partners/CHI-kissclipart-navy-pier-logo-clipart-chicago-shakespeare-theater-e550ac399dac0a24.jpg"
echo "Renaming: DSCF4385.jpg → JOR-DSCF4385.jpg"
# mv "public/Website beloveful.com/Middle East/Jordan/DSCF4385.jpg" "public/Website beloveful.com/Middle East/Jordan/JOR-DSCF4385.jpg"
echo "Renaming: DSCF4430.jpg → JOR-DSCF4430.jpg"
# mv "public/Website beloveful.com/Middle East/Jordan/DSCF4430.jpg" "public/Website beloveful.com/Middle East/Jordan/JOR-DSCF4430.jpg"
echo "Renaming: DSCF4488.jpg → JOR-DSCF4488.jpg"
# mv "public/Website beloveful.com/Middle East/Jordan/DSCF4488.jpg" "public/Website beloveful.com/Middle East/Jordan/JOR-DSCF4488.jpg"
echo "Renaming: DSCF4537-Website-2.jpg → JOR-DSCF4537-Website-2.jpg"
# mv "public/Website beloveful.com/Middle East/Jordan/DSCF4537-Website-2.jpg" "public/Website beloveful.com/Middle East/Jordan/JOR-DSCF4537-Website-2.jpg"
echo "Renaming: DSCF4561.jpg → JOR-DSCF4561.jpg"
# mv "public/Website beloveful.com/Middle East/Jordan/DSCF4561.jpg" "public/Website beloveful.com/Middle East/Jordan/JOR-DSCF4561.jpg"
echo "Renaming: DSCF4610-4.jpg → JOR-DSCF4610-4.jpg"
# mv "public/Website beloveful.com/Middle East/Jordan/DSCF4610-4.jpg" "public/Website beloveful.com/Middle East/Jordan/JOR-DSCF4610-4.jpg"
echo "Renaming: DSCF4619.jpg → JOR-DSCF4619.jpg"
# mv "public/Website beloveful.com/Middle East/Jordan/DSCF4619.jpg" "public/Website beloveful.com/Middle East/Jordan/JOR-DSCF4619.jpg"
echo "Renaming: DSCF4640.jpg → JOR-DSCF4640.jpg"
# mv "public/Website beloveful.com/Middle East/Jordan/DSCF4640.jpg" "public/Website beloveful.com/Middle East/Jordan/JOR-DSCF4640.jpg"
echo "Renaming: DSCF4694.jpg → JOR-DSCF4694.jpg"
# mv "public/Website beloveful.com/Middle East/Jordan/DSCF4694.jpg" "public/Website beloveful.com/Middle East/Jordan/JOR-DSCF4694.jpg"
echo "Renaming: JDN-4455.jpg → JOR-JDN-4455.jpg"
# mv "public/Website beloveful.com/Middle East/Jordan/JDN-4455.jpg" "public/Website beloveful.com/Middle East/Jordan/JOR-JDN-4455.jpg"
echo "Renaming: JDN-4461.jpg → JOR-JDN-4461.jpg"
# mv "public/Website beloveful.com/Middle East/Jordan/JDN-4461.jpg" "public/Website beloveful.com/Middle East/Jordan/JOR-JDN-4461.jpg"
echo "Renaming: DSCF0396.jpg → CHI-DSCF0396.jpg"
# mv "public/Website beloveful.com/North America/Chicago/DSCF0396.jpg" "public/Website beloveful.com/North America/Chicago/CHI-DSCF0396.jpg"
echo "Renaming: DSCF0926.jpg → CHI-DSCF0926.jpg"
# mv "public/Website beloveful.com/North America/Chicago/DSCF0926.jpg" "public/Website beloveful.com/North America/Chicago/CHI-DSCF0926.jpg"
echo "Renaming: DSCF0942.jpg → CHI-DSCF0942.jpg"
# mv "public/Website beloveful.com/North America/Chicago/DSCF0942.jpg" "public/Website beloveful.com/North America/Chicago/CHI-DSCF0942.jpg"
echo "Renaming: DSCF1007.jpg → CHI-DSCF1007.jpg"
# mv "public/Website beloveful.com/North America/Chicago/DSCF1007.jpg" "public/Website beloveful.com/North America/Chicago/CHI-DSCF1007.jpg"
echo "Renaming: DSCF1196.jpg → CHI-DSCF1196.jpg"
# mv "public/Website beloveful.com/North America/Chicago/DSCF1196.jpg" "public/Website beloveful.com/North America/Chicago/CHI-DSCF1196.jpg"
echo "Renaming: DSCF1841.jpg → CHI-DSCF1841.jpg"
# mv "public/Website beloveful.com/North America/Chicago/DSCF1841.jpg" "public/Website beloveful.com/North America/Chicago/CHI-DSCF1841.jpg"
echo "Renaming: DSCF1980.jpg → CHI-DSCF1980.jpg"
# mv "public/Website beloveful.com/North America/Chicago/DSCF1980.jpg" "public/Website beloveful.com/North America/Chicago/CHI-DSCF1980.jpg"
echo "Renaming: DSCF2587.jpg → CHI-DSCF2587.jpg"
# mv "public/Website beloveful.com/North America/Chicago/DSCF2587.jpg" "public/Website beloveful.com/North America/Chicago/CHI-DSCF2587.jpg"
echo "Renaming: DSCF5972.jpg → CHI-DSCF5972.jpg"
# mv "public/Website beloveful.com/North America/Chicago/DSCF5972.jpg" "public/Website beloveful.com/North America/Chicago/CHI-DSCF5972.jpg"
echo "Renaming: DSCF7113.jpg → CHI-DSCF7113.jpg"
# mv "public/Website beloveful.com/North America/Chicago/DSCF7113.jpg" "public/Website beloveful.com/North America/Chicago/CHI-DSCF7113.jpg"
echo "Renaming: DSCF8938.jpg → CHI-DSCF8938.jpg"
# mv "public/Website beloveful.com/North America/Chicago/DSCF8938.jpg" "public/Website beloveful.com/North America/Chicago/CHI-DSCF8938.jpg"
echo "Renaming: DSCF9626.jpg → CHI-DSCF9626.jpg"
# mv "public/Website beloveful.com/North America/Chicago/DSCF9626.jpg" "public/Website beloveful.com/North America/Chicago/CHI-DSCF9626.jpg"
echo "Renaming: DSCF9897-2.jpg → CHI-DSCF9897-2.jpg"
# mv "public/Website beloveful.com/North America/Chicago/DSCF9897-2.jpg" "public/Website beloveful.com/North America/Chicago/CHI-DSCF9897-2.jpg"
echo "Renaming: Fountain Fairy.jpg → CHI-Fountain Fairy.jpg"
# mv "public/Website beloveful.com/North America/Chicago/Fountain Fairy.jpg" "public/Website beloveful.com/North America/Chicago/CHI-Fountain Fairy.jpg"
echo "Renaming: Marina City-10-16-16.jpg → CHI-Marina City-10-16-16.jpg"
# mv "public/Website beloveful.com/North America/Chicago/Marina City-10-16-16.jpg" "public/Website beloveful.com/North America/Chicago/CHI-Marina City-10-16-16.jpg"
echo "Renaming: Tony Menias-Marathoners.jpg → CHI-Tony Menias-Marathoners.jpg"
# mv "public/Website beloveful.com/North America/Chicago/Tony Menias-Marathoners.jpg" "public/Website beloveful.com/North America/Chicago/CHI-Tony Menias-Marathoners.jpg"
echo "Renaming: Tony_Menias 1.jpg → CHI-Tony_Menias 1.jpg"
# mv "public/Website beloveful.com/North America/Chicago/Tony_Menias 1.jpg" "public/Website beloveful.com/North America/Chicago/CHI-Tony_Menias 1.jpg"
echo "Renaming: _DSF9855.jpg → CHI-_DSF9855.jpg"
# mv "public/Website beloveful.com/North America/Chicago/_DSF9855.jpg" "public/Website beloveful.com/North America/Chicago/CHI-_DSF9855.jpg"
echo "Renaming: 08-09-NYC.jpg → NYC-08-09-NYC.jpg"
# mv "public/Website beloveful.com/North America/New York/08-09-NYC.jpg" "public/Website beloveful.com/North America/New York/NYC-08-09-NYC.jpg"
echo "Renaming: Btw the Lines.jpg → NYC-Btw the Lines.jpg"
# mv "public/Website beloveful.com/North America/New York/Btw the Lines.jpg" "public/Website beloveful.com/North America/New York/NYC-Btw the Lines.jpg"
echo "Renaming: DSCF1459.jpg → NYC-DSCF1459.jpg"
# mv "public/Website beloveful.com/North America/New York/DSCF1459.jpg" "public/Website beloveful.com/North America/New York/NYC-DSCF1459.jpg"
echo "Renaming: DSCF7931.jpg → NYC-DSCF7931.jpg"
# mv "public/Website beloveful.com/North America/New York/DSCF7931.jpg" "public/Website beloveful.com/North America/New York/NYC-DSCF7931.jpg"
echo "Renaming: DSCF8189.jpg → NYC-DSCF8189.jpg"
# mv "public/Website beloveful.com/North America/New York/DSCF8189.jpg" "public/Website beloveful.com/North America/New York/NYC-DSCF8189.jpg"
echo "Renaming: DSCF8922.jpg → NYC-DSCF8922.jpg"
# mv "public/Website beloveful.com/North America/New York/DSCF8922.jpg" "public/Website beloveful.com/North America/New York/NYC-DSCF8922.jpg"
echo "Renaming: Into the Rabbit Hole.jpg → NYC-Into the Rabbit Hole.jpg"
# mv "public/Website beloveful.com/North America/New York/Into the Rabbit Hole.jpg" "public/Website beloveful.com/North America/New York/NYC-Into the Rabbit Hole.jpg"
echo "Renaming: Snack Time.jpg → NYC-Snack Time.jpg"
# mv "public/Website beloveful.com/North America/New York/Snack Time.jpg" "public/Website beloveful.com/North America/New York/NYC-Snack Time.jpg"
echo "Renaming: Stop Light.jpg → NYC-Stop Light.jpg"
# mv "public/Website beloveful.com/North America/New York/Stop Light.jpg" "public/Website beloveful.com/North America/New York/NYC-Stop Light.jpg"
echo "Renaming: _DSF6412.jpg → NYC-_DSF6412.jpg"
# mv "public/Website beloveful.com/North America/New York/_DSF6412.jpg" "public/Website beloveful.com/North America/New York/NYC-_DSF6412.jpg"
echo "Renaming: _DSF6532.jpg → NYC-_DSF6532.jpg"
# mv "public/Website beloveful.com/North America/New York/_DSF6532.jpg" "public/Website beloveful.com/North America/New York/NYC-_DSF6532.jpg"
echo "Renaming: untitled-107.jpg → NYC-untitled-107.jpg"
# mv "public/Website beloveful.com/North America/New York/untitled-107.jpg" "public/Website beloveful.com/North America/New York/NYC-untitled-107.jpg"
echo "Renaming: _DSF5908.jpg → ARG-_DSF5908.jpg"
# mv "public/Website beloveful.com/South America/Argentina/_DSF5908.jpg" "public/Website beloveful.com/South America/Argentina/ARG-_DSF5908.jpg"
echo "Renaming: _DSF5960.jpg → ARG-_DSF5960.jpg"
# mv "public/Website beloveful.com/South America/Argentina/_DSF5960.jpg" "public/Website beloveful.com/South America/Argentina/ARG-_DSF5960.jpg"
echo "Renaming: _DSF6120.jpg → ARG-_DSF6120.jpg"
# mv "public/Website beloveful.com/South America/Argentina/_DSF6120.jpg" "public/Website beloveful.com/South America/Argentina/ARG-_DSF6120.jpg"
echo "Renaming: _DSF6182-2.jpg → ARG-_DSF6182-2.jpg"
# mv "public/Website beloveful.com/South America/Argentina/_DSF6182-2.jpg" "public/Website beloveful.com/South America/Argentina/ARG-_DSF6182-2.jpg"
echo "Renaming: _DSF6263.jpg → ARG-_DSF6263.jpg"
# mv "public/Website beloveful.com/South America/Argentina/_DSF6263.jpg" "public/Website beloveful.com/South America/Argentina/ARG-_DSF6263.jpg"
echo "Renaming: _DSF6444-2.jpg → ARG-_DSF6444-2.jpg"
# mv "public/Website beloveful.com/South America/Argentina/_DSF6444-2.jpg" "public/Website beloveful.com/South America/Argentina/ARG-_DSF6444-2.jpg"
echo "Renaming: _DSF6559.jpg → ARG-_DSF6559.jpg"
# mv "public/Website beloveful.com/South America/Argentina/_DSF6559.jpg" "public/Website beloveful.com/South America/Argentina/ARG-_DSF6559.jpg"
echo "Renaming: _DSF6704.jpg → ARG-_DSF6704.jpg"
# mv "public/Website beloveful.com/South America/Argentina/_DSF6704.jpg" "public/Website beloveful.com/South America/Argentina/ARG-_DSF6704.jpg"
echo "Renaming: _DSF6728-2.jpg → ARG-_DSF6728-2.jpg"
# mv "public/Website beloveful.com/South America/Argentina/_DSF6728-2.jpg" "public/Website beloveful.com/South America/Argentina/ARG-_DSF6728-2.jpg"
echo "Renaming: _DSF6742-2.jpg → ARG-_DSF6742-2.jpg"
# mv "public/Website beloveful.com/South America/Argentina/_DSF6742-2.jpg" "public/Website beloveful.com/South America/Argentina/ARG-_DSF6742-2.jpg"
echo "Renaming: _DSF6798-3.jpg → ARG-_DSF6798-3.jpg"
# mv "public/Website beloveful.com/South America/Argentina/_DSF6798-3.jpg" "public/Website beloveful.com/South America/Argentina/ARG-_DSF6798-3.jpg"
echo "Renaming: _DSF6820.jpg → ARG-_DSF6820.jpg"
# mv "public/Website beloveful.com/South America/Argentina/_DSF6820.jpg" "public/Website beloveful.com/South America/Argentina/ARG-_DSF6820.jpg"
echo "Renaming: _DSF6993 copy.jpg → ARG-_DSF6993 copy.jpg"
# mv "public/Website beloveful.com/South America/Argentina/_DSF6993 copy.jpg" "public/Website beloveful.com/South America/Argentina/ARG-_DSF6993 copy.jpg"
echo "Renaming: _DSF6993.jpg → ARG-_DSF6993.jpg"
# mv "public/Website beloveful.com/South America/Argentina/_DSF6993.jpg" "public/Website beloveful.com/South America/Argentina/ARG-_DSF6993.jpg"
echo "Renaming: _DSF7175-4.jpg → ARG-_DSF7175-4.jpg"
# mv "public/Website beloveful.com/South America/Argentina/_DSF7175-4.jpg" "public/Website beloveful.com/South America/Argentina/ARG-_DSF7175-4.jpg"
echo "Renaming: _DSF7204-5.jpg → ARG-_DSF7204-5.jpg"
# mv "public/Website beloveful.com/South America/Argentina/_DSF7204-5.jpg" "public/Website beloveful.com/South America/Argentina/ARG-_DSF7204-5.jpg"
echo "Renaming: _DSF7244-3.jpg → ARG-_DSF7244-3.jpg"
# mv "public/Website beloveful.com/South America/Argentina/_DSF7244-3.jpg" "public/Website beloveful.com/South America/Argentina/ARG-_DSF7244-3.jpg"
echo "Renaming: _DSF8239-3.jpg → ARG-_DSF8239-3.jpg"
# mv "public/Website beloveful.com/South America/Argentina/_DSF8239-3.jpg" "public/Website beloveful.com/South America/Argentina/ARG-_DSF8239-3.jpg"
echo "Renaming: _DSF8320.jpg → ARG-_DSF8320.jpg"
# mv "public/Website beloveful.com/South America/Argentina/_DSF8320.jpg" "public/Website beloveful.com/South America/Argentina/ARG-_DSF8320.jpg"
echo "Renaming: _DSF8547.jpg → ARG-_DSF8547.jpg"
# mv "public/Website beloveful.com/South America/Argentina/_DSF8547.jpg" "public/Website beloveful.com/South America/Argentina/ARG-_DSF8547.jpg"
echo "Renaming: breaks-chicago.jpg → CHI-breaks-chicago.jpg"
# mv "public/Website beloveful.com/clients/breaks-chicago.jpg" "public/Website beloveful.com/clients/CHI-breaks-chicago.jpg"
echo "Renaming: kissclipart-navy-pier-logo-clipart-chicago-shakespeare-theater-e550ac399dac0a24.jpg → CHI-kissclipart-navy-pier-logo-clipart-chicago-shakespeare-theater-e550ac399dac0a24.jpg"
# mv "public/Website beloveful.com/clients/kissclipart-navy-pier-logo-clipart-chicago-shakespeare-theater-e550ac399dac0a24.jpg" "public/Website beloveful.com/clients/CHI-kissclipart-navy-pier-logo-clipart-chicago-shakespeare-theater-e550ac399dac0a24.jpg"
