#!/bin/bash

# Smart Filename Cleanup Script
# Focuses on high-impact fixes for country detection

echo "Starting smart filename cleanup..."

echo "🎯 11-21-EGY-262 2.jpg → EGY-262-2.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/11-21-EGY-262 2.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/EGY-262-2.jpg"
echo "🎯 11-16-EGY-1107.jpg → EGY-1107.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/11-16-EGY-1107.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/EGY-1107.jpg"
echo "🎯 11-16-EGY-1128.jpg → EGY-1128.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/11-16-EGY-1128.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/EGY-1128.jpg"
echo "🎯 11-17-EGY-172.jpg → EGY-172-egypt.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/11-17-EGY-172.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/EGY-172-egypt.jpg"
echo "🎯 11-17-EGY-550.jpg → EGY-550.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/11-17-EGY-550.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/EGY-550.jpg"
echo "🎯 11-17-EGY-598.jpg → EGY-598.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/11-17-EGY-598.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/EGY-598.jpg"
echo "🎯 11-18-EGY-110.jpg → EGY-110-egypt.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/11-18-EGY-110.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/EGY-110-egypt.jpg"
echo "🎯 11-28-EGY-508.jpg → EGY-508.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/11-28-EGY-508.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/EGY-508.jpg"
echo "🎯 11-28-EGY-512.jpg → EGY-512.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/11-28-EGY-512.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/EGY-512.jpg"
echo "🎯 12-01-EGY-150.jpg → EGY-150.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/12-01-EGY-150.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/EGY-150.jpg"
echo "🎯 12-14-EGY-342.jpg → EGY-342.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/12-14-EGY-342.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/EGY-342.jpg"
echo "🧹 08-09-NYC.jpg → NYC.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/New York/08-09-NYC.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/New York/NYC.jpg"
echo "🧹 _DSF4413 (1).jpg → _DSF4413-1.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Thailand/_DSF4413 (1).jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Thailand/_DSF4413-1.jpg"
echo "🧹 pngegg (1).png → pngegg-1.png"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Clients & Partners/pngegg (1).png" "/home/camo/new/beloveful.com/public/Website beloveful.com/Clients & Partners/pngegg-1.png"
echo "🧹 pngegg (2).png → pngegg-2.png"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Clients & Partners/pngegg (2).png" "/home/camo/new/beloveful.com/public/Website beloveful.com/Clients & Partners/pngegg-2.png"
echo "🧹 5x7s-Shapes & Shadows.jpg → 5x7s-Shapes-Shadows.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/5x7s-Shapes & Shadows.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/5x7s-Shapes-Shadows.jpg"
echo "🧹 pngegg (1).png → pngegg-1-clients.png"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/clients/pngegg (1).png" "/home/camo/new/beloveful.com/public/Website beloveful.com/clients/pngegg-1-clients.png"
echo "🧹 pngegg (2).png → pngegg-2-clients.png"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/clients/pngegg (2).png" "/home/camo/new/beloveful.com/public/Website beloveful.com/clients/pngegg-2-clients.png"
echo "🧹 EGY-148 copy.jpg → EGY-148-copy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/EGY-148 copy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/EGY-148-copy.jpg"
echo "🧹 EGY-53 copy.jpg → EGY-53-copy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/EGY-53 copy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/EGY-53-copy.jpg"
echo "🧹 EGY-565 copy.jpg → EGY-565-copy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/EGY-565 copy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/EGY-565-copy.jpg"
echo "🧹 EGY-61 copy.jpg → EGY-61-copy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/EGY-61 copy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/EGY-61-copy.jpg"
echo "🧹 Sense of Scale.jpg → Sense-of-Scale.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/Sense of Scale.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/Sense-of-Scale.jpg"
echo "🧹 Toiny Mernias Buoyancy1.jpg → Toiny-Mernias-Buoyancy1.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/Toiny Mernias Buoyancy1.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/Toiny-Mernias-Buoyancy1.jpg"
echo "🧹 Tony Menias - Tuk Tuk Graveyard .jpg → Tony-Menias-Tuk-Tuk-Graveyard.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/Tony Menias - Tuk Tuk Graveyard .jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/Tony-Menias-Tuk-Tuk-Graveyard.jpg"
echo "🧹 Tony Menias-Buoyancy.jpg → Tony-Menias-Buoyancy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/Tony Menias-Buoyancy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Egypt/Tony-Menias-Buoyancy.jpg"
echo "🧹 Morocco-Hide n Seek.jpg → Morocco-Hide-n-Seek.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Morocco/Morocco-Hide n Seek.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Africa/Morocco/Morocco-Hide-n-Seek.jpg"
echo "🧹 HK-5841 copy.jpg → HK-5841-copy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Hong Kong/HK-5841 copy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Hong Kong/HK-5841-copy.jpg"
echo "🧹 HK-Pastel Playground 2-6570.jpg → HK-Pastel-Playground-2-6570.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Hong Kong/HK-Pastel Playground 2-6570.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Hong Kong/HK-Pastel-Playground-2-6570.jpg"
echo "🧹 HK-Pastel Playground 3-6617.jpg → HK-Pastel-Playground-3-6617.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Hong Kong/HK-Pastel Playground 3-6617.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Hong Kong/HK-Pastel-Playground-3-6617.jpg"
echo "🧹 HK-Pastel Playground 4-6559.jpg → HK-Pastel-Playground-4-6559.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Hong Kong/HK-Pastel Playground 4-6559.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Hong Kong/HK-Pastel-Playground-4-6559.jpg"
echo "🧹 HK-Unexpected perspective-6919.jpg → HK-Unexpected-perspective-6919.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Hong Kong/HK-Unexpected perspective-6919.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Hong Kong/HK-Unexpected-perspective-6919.jpg"
echo "🧹 Pastel Playground.jpg → Pastel-Playground.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Hong Kong/Pastel Playground.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Hong Kong/Pastel-Playground.jpg"
echo "🧹 _DSF3449 copy.jpg → _DSF3449-copy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Japan/_DSF3449 copy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Japan/_DSF3449-copy.jpg"
echo "🧹 Bridge to Enlightenment.jpg → Bridge-to-Enlightenment.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Myanmar/Bridge to Enlightenment.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Myanmar/Bridge-to-Enlightenment.jpg"
echo "🧹 DSCF0098 copy.jpg → DSCF0098-copy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Myanmar/DSCF0098 copy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Myanmar/DSCF0098-copy.jpg"
echo "🧹 DSCF0214 copy.jpg → DSCF0214-copy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Myanmar/DSCF0214 copy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Myanmar/DSCF0214-copy.jpg"
echo "🧹 MYA-Morning Catch.jpg → MYA-Morning-Catch.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Myanmar/MYA-Morning Catch.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Myanmar/MYA-Morning-Catch.jpg"
echo "🧹 Tony Menias-Fly.jpg → Tony-Menias-Fly.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Myanmar/Tony Menias-Fly.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Myanmar/Tony-Menias-Fly.jpg"
echo "🧹 NEP-Silent Stare.jpg → NEP-Silent-Stare.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Nepal/NEP-Silent Stare.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Nepal/NEP-Silent-Stare.jpg"
echo "🧹 Simpler Times.jpg → Simpler-Times.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Thailand/Simpler Times.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Thailand/Simpler-Times.jpg"
echo "🧹 Lazy Sunday.jpg → Lazy-Sunday.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Vietnam/Lazy Sunday.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Vietnam/Lazy-Sunday.jpg"
echo "🧹 Vietnam Valley.jpg → Vietnam-Valley.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Vietnam/Vietnam Valley.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Asia/Vietnam/Vietnam-Valley.jpg"
echo "🧹 MEX-178 copy.jpg → MEX-178-copy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Central America & Caribbean/Mexico/MEX-178 copy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Central America & Caribbean/Mexico/MEX-178-copy.jpg"
echo "🧹 MEX-56 copy.jpg → MEX-56-copy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Central America & Caribbean/Mexico/MEX-56 copy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Central America & Caribbean/Mexico/MEX-56-copy.jpg"
echo "🧹 MEX-Miss Technicolor-8.jpg → MEX-Miss-Technicolor-8.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Central America & Caribbean/Mexico/MEX-Miss Technicolor-8.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Central America & Caribbean/Mexico/MEX-Miss-Technicolor-8.jpg"
echo "🧹 2019-02-05 10.22.37 pm.png → 2019-02-05-10.22.37-pm.png"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Clients & Partners/2019-02-05 10.22.37 pm.png" "/home/camo/new/beloveful.com/public/Website beloveful.com/Clients & Partners/2019-02-05-10.22.37-pm.png"
echo "🧹 DSCF3088 copy.jpg → DSCF3088-copy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Erasing Borders/DSCF3088 copy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Erasing Borders/DSCF3088-copy.jpg"
echo "🧹 FRA-DSCF0103 copy.jpg → FRA-DSCF0103-copy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Erasing Borders/FRA-DSCF0103 copy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Erasing Borders/FRA-DSCF0103-copy.jpg"
echo "🧹 Greece-DSCF3935 copy 3.jpg → Greece-DSCF3935-copy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Erasing Borders/Greece-DSCF3935 copy 3.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Erasing Borders/Greece-DSCF3935-copy.jpg"
echo "🧹 MOR-IMG_5248 copy.jpg → MOR-IMG_5248-copy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Erasing Borders/MOR-IMG_5248 copy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Erasing Borders/MOR-IMG_5248-copy.jpg"
echo "🧹 MYA-DSCF0783 copy.jpg → MYA-DSCF0783-copy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Erasing Borders/MYA-DSCF0783 copy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Erasing Borders/MYA-DSCF0783-copy.jpg"
echo "🧹 MYA-DSCF9634 copy.jpg → MYA-DSCF9634-copy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Erasing Borders/MYA-DSCF9634 copy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Erasing Borders/MYA-DSCF9634-copy.jpg"
echo "🧹 NEP-DSCF8737 copy.jpg → NEP-DSCF8737-copy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Erasing Borders/NEP-DSCF8737 copy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Erasing Borders/NEP-DSCF8737-copy.jpg"
echo "🧹 NEP-Silent Stare copy.jpg → NEP-Silent-Stare-copy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Erasing Borders/NEP-Silent Stare copy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Erasing Borders/NEP-Silent-Stare-copy.jpg"
echo "🧹 NatureVSNurture copy.jpg → NatureVSNurture-copy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Erasing Borders/NatureVSNurture copy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Erasing Borders/NatureVSNurture-copy.jpg"
echo "🧹 NyC-DSCF8922 copy 2.jpg → NyC-DSCF8922-copy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Erasing Borders/NyC-DSCF8922 copy 2.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Erasing Borders/NyC-DSCF8922-copy.jpg"
echo "🧹 PAL-DSCF3675 copy.jpg → PAL-DSCF3675-copy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Erasing Borders/PAL-DSCF3675 copy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Erasing Borders/PAL-DSCF3675-copy.jpg"
echo "🧹 PHI-1662 copy.jpg → PHI-1662-copy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Erasing Borders/PHI-1662 copy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Erasing Borders/PHI-1662-copy.jpg"
echo "🧹 THAI-DSCF3890 copy.jpg → THAI-DSCF3890-copy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Erasing Borders/THAI-DSCF3890 copy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Erasing Borders/THAI-DSCF3890-copy.jpg"
echo "🧹 Tony Menias - Two Girls in Window.jpg → Tony-Menias-Two-Girls-in-Window.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Erasing Borders/Tony Menias - Two Girls in Window.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Erasing Borders/Tony-Menias-Two-Girls-in-Window.jpg"
echo "🧹 Vietnam-DSCF8153 copy.jpg → Vietnam-DSCF8153-copy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Erasing Borders/Vietnam-DSCF8153 copy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Erasing Borders/Vietnam-DSCF8153-copy.jpg"
echo "🧹 DSCF3407 copy.jpg → DSCF3407-copy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Greece/DSCF3407 copy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Greece/DSCF3407-copy.jpg"
echo "🧹 DSCF3885 copy 2.jpg → DSCF3885-copy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Italy/DSCF3885 copy 2.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Italy/DSCF3885-copy.jpg"
echo "🧹 DSCF3885 copy.jpg → DSCF3885-copy-italy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Italy/DSCF3885 copy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Italy/DSCF3885-copy-italy.jpg"
echo "🧹 ITA-6300 copy.jpg → ITA-6300-copy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Italy/ITA-6300 copy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Europe & Scandinavia/Italy/ITA-6300-copy.jpg"
echo "🧹 Calm Before The Storm.jpg → Calm-Before-The-Storm.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Homepage/Desktop Landscape/Calm Before The Storm.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Homepage/Desktop Landscape/Calm-Before-The-Storm.jpg"
echo "🧹 Headless Horseman-11-21-DSCF1337.jpg → Headless-Horseman-11-21-DSCF1337.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Homepage/Desktop Landscape/Headless Horseman-11-21-DSCF1337.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Homepage/Desktop Landscape/Headless-Horseman-11-21-DSCF1337.jpg"
echo "🧹 Simpler Times.jpg → Simpler-Times-desktopl.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Homepage/Desktop Landscape/Simpler Times.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Homepage/Desktop Landscape/Simpler-Times-desktopl.jpg"
echo "🧹 Snack Time.jpg → Snack-Time.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Homepage/Desktop Landscape/Snack Time.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Homepage/Desktop Landscape/Snack-Time.jpg"
echo "🧹 Tony Menias-Fly.jpg → Tony-Menias-Fly-desktopl.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Homepage/Desktop Landscape/Tony Menias-Fly.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Homepage/Desktop Landscape/Tony-Menias-Fly-desktopl.jpg"
echo "🧹 Into the Rabbit Hole.jpg → Into-the-Rabbit-Hole.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Homepage/Mobile Portrait/Into the Rabbit Hole.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Homepage/Mobile Portrait/Into-the-Rabbit-Hole.jpg"
echo "🧹 Madame Jodhpur-03-19-DSCF7654.jpg → Madame-Jodhpur-03-19-DSCF7654.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Homepage/Mobile Portrait/Madame Jodhpur-03-19-DSCF7654.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Homepage/Mobile Portrait/Madame-Jodhpur-03-19-DSCF7654.jpg"
echo "🧹 Pastel Playground.jpg → Pastel-Playground-mobilepo.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Homepage/Mobile Portrait/Pastel Playground.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Homepage/Mobile Portrait/Pastel-Playground-mobilepo.jpg"
echo "🧹 Sense of Scale.jpg → Sense-of-Scale-mobilepo.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Homepage/Mobile Portrait/Sense of Scale.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Homepage/Mobile Portrait/Sense-of-Scale-mobilepo.jpg"
echo "🧹 Beloveful black transparent.png → Beloveful-black-transparent.png"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Logo/Beloveful black transparent.png" "/home/camo/new/beloveful.com/public/Website beloveful.com/Logo/Beloveful-black-transparent.png"
echo "🧹 Beloveful copy 2.png → Beloveful-copy.png"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Logo/Beloveful copy 2.png" "/home/camo/new/beloveful.com/public/Website beloveful.com/Logo/Beloveful-copy.png"
echo "🧹 Beloveful copy 3.png → Beloveful-copy-logo.png"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Logo/Beloveful copy 3.png" "/home/camo/new/beloveful.com/public/Website beloveful.com/Logo/Beloveful-copy-logo.png"
echo "🧹 Beloveful copy 6.png → Beloveful-copy-websiteb.png"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Logo/Beloveful copy 6.png" "/home/camo/new/beloveful.com/public/Website beloveful.com/Logo/Beloveful-copy-websiteb.png"
echo "🧹 Beloveful copy.png → Beloveful-copy-1.png"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Logo/Beloveful copy.png" "/home/camo/new/beloveful.com/public/Website beloveful.com/Logo/Beloveful-copy-1.png"
echo "🧹 IMG SMALl.jpg → IMG-SMALl.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Logo/IMG SMALl.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Logo/IMG-SMALl.jpg"
echo "🧹 IMG_0007 copy.JPG → IMG_0007-copy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Logo/IMG_0007 copy.JPG" "/home/camo/new/beloveful.com/public/Website beloveful.com/Logo/IMG_0007-copy.jpg"
echo "🧹 IMG_4610 copy.jpg copy 3.png → IMG_4610-copy.jpg-copy.png"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Logo/IMG_4610 copy.jpg copy 3.png" "/home/camo/new/beloveful.com/public/Website beloveful.com/Logo/IMG_4610-copy.jpg-copy.png"
echo "🧹 Beloveful white transparent.png → Beloveful-white-transparent.png"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Logo/White/Beloveful white transparent.png" "/home/camo/new/beloveful.com/public/Website beloveful.com/Logo/White/Beloveful-white-transparent.png"
echo "🧹 Smaller 2.png → Smaller-2.png"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Logo/White/Smaller 2.png" "/home/camo/new/beloveful.com/public/Website beloveful.com/Logo/White/Smaller-2.png"
echo "🧹 Smaller Logo.png → Smaller-Logo.png"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Logo/White/Smaller Logo.png" "/home/camo/new/beloveful.com/public/Website beloveful.com/Logo/White/Smaller-Logo.png"
echo "🧹 beloveful logo inverted 75_ opacity.png → beloveful-logo-inverted-75_-opacity.png"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Logo/beloveful logo inverted 75_ opacity.png" "/home/camo/new/beloveful.com/public/Website beloveful.com/Logo/beloveful-logo-inverted-75_-opacity.png"
echo "🧹 CHI-3 copy.jpg → CHI-3-copy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/Chicago/CHI-3 copy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/Chicago/CHI-3-copy.jpg"
echo "🧹 CHI-415 copy.jpg → CHI-415-copy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/Chicago/CHI-415 copy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/Chicago/CHI-415-copy.jpg"
echo "🧹 CHI-7876 copy.jpg → CHI-7876-copy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/Chicago/CHI-7876 copy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/Chicago/CHI-7876-copy.jpg"
echo "🧹 Fountain Fairy.jpg → Fountain-Fairy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/Chicago/Fountain Fairy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/Chicago/Fountain-Fairy.jpg"
echo "🧹 Marina City-10-16-16.jpg → Marina-City-10-16-16.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/Chicago/Marina City-10-16-16.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/Chicago/Marina-City-10-16-16.jpg"
echo "🧹 Tony Menias-Marathoners.jpg → Tony-Menias-Marathoners.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/Chicago/Tony Menias-Marathoners.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/Chicago/Tony-Menias-Marathoners.jpg"
echo "🧹 Tony_Menias 1.jpg → Tony_Menias-1.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/Chicago/Tony_Menias 1.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/Chicago/Tony_Menias-1.jpg"
echo "🧹 Btw the Lines.jpg → Btw-the-Lines.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/New York/Btw the Lines.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/New York/Btw-the-Lines.jpg"
echo "🧹 Into the Rabbit Hole.jpg → Into-the-Rabbit-Hole-newyork.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/New York/Into the Rabbit Hole.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/New York/Into-the-Rabbit-Hole-newyork.jpg"
echo "🧹 NYC-313 copy.jpg → NYC-313-copy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/New York/NYC-313 copy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/New York/NYC-313-copy.jpg"
echo "🧹 Snack Time.jpg → Snack-Time-newyork.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/New York/Snack Time.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/New York/Snack-Time-newyork.jpg"
echo "🧹 Stop Light.jpg → Stop-Light.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/New York/Stop Light.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/North America/New York/Stop-Light.jpg"
echo "🧹 5x7s Life_s a Highway.jpg → 5x7s-Life_s-a-Highway.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/5x7s Life_s a Highway.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/5x7s-Life_s-a-Highway.jpg"
echo "🧹 5x7s-Family Meal.jpg → 5x7s-Family-Meal.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/5x7s-Family Meal.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/5x7s-Family-Meal.jpg"
echo "🧹 5x7s-Hide N Seek.jpg → 5x7s-Hide-N-Seek.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/5x7s-Hide N Seek.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/5x7s-Hide-N-Seek.jpg"
echo "🧹 5x7s-Into the Rabbit Hole.jpg → 5x7s-Into-the-Rabbit-Hole.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/5x7s-Into the Rabbit Hole.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/5x7s-Into-the-Rabbit-Hole.jpg"
echo "🧹 5x7s-Long Day.jpg → 5x7s-Long-Day.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/5x7s-Long Day.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/5x7s-Long-Day.jpg"
echo "🧹 5x7s-Mag Mile.jpg → 5x7s-Mag-Mile.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/5x7s-Mag Mile.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/5x7s-Mag-Mile.jpg"
echo "🧹 5x7s-Ville de Lamour.jpg → 5x7s-Ville-de-Lamour.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/5x7s-Ville de Lamour.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/5x7s-Ville-de-Lamour.jpg"
echo "🧹 Between The Lines 5x7.jpg → Between-The-Lines-5x7.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/Between The Lines 5x7.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/Between-The-Lines-5x7.jpg"
echo "🧹 NY Slice 5x7.jpg → NY-Slice-5x7.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/NY Slice 5x7.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/NY-Slice-5x7.jpg"
echo "🧹 Pressed 5x7.jpg → Pressed-5x7.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/Pressed 5x7.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/Pressed-5x7.jpg"
echo "🧹 She Waited 5x7.jpg → She-Waited-5x7.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/She Waited 5x7.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/She-Waited-5x7.jpg"
echo "🧹 Shy or Shame 5x7.jpg → Shy-or-Shame-5x7.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/Shy or Shame 5x7.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/Shy-or-Shame-5x7.jpg"
echo "🧹 Sun Maiden 5x7.jpg → Sun-Maiden-5x7.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/Sun Maiden 5x7.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/Sun-Maiden-5x7.jpg"
echo "🧹 Towel-Head 5x7.jpg → Towel-Head-5x7.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/Towel-Head 5x7.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/Towel-Head-5x7.jpg"
echo "🧹 Violet Canine 5x7.jpg → Violet-Canine-5x7.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/Violet Canine 5x7.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/Violet-Canine-5x7.jpg"
echo "🧹 snack time 5x7.jpg → snack-time-5x7.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/snack time 5x7.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Open Edition size 5x7/Open Edition 5x7/snack-time-5x7.jpg"
echo "🧹 _DSF6993 copy.jpg → _DSF6993-copy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/South America/Argentina/_DSF6993 copy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/South America/Argentina/_DSF6993-copy.jpg"
echo "🧹 Copy of CHI-0871.jpg → Copy-of-CHI-0871.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy of CHI-0871.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy-of-CHI-0871.jpg"
echo "🧹 Copy of CHI-09-19-DSCF5133.jpg → Copy-of-CHI-09-19-DSCF5133.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy of CHI-09-19-DSCF5133.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy-of-CHI-09-19-DSCF5133.jpg"
echo "🧹 Copy of CHI-2084-Website-2.jpg → Copy-of-CHI-2084-Website-2.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy of CHI-2084-Website-2.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy-of-CHI-2084-Website-2.jpg"
echo "🧹 Copy of CHI-3.jpg → Copy-of-CHI-3.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy of CHI-3.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy-of-CHI-3.jpg"
echo "🧹 Copy of CHI-359.jpg → Copy-of-CHI-359.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy of CHI-359.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy-of-CHI-359.jpg"
echo "🧹 Copy of CHI-5041.jpg → Copy-of-CHI-5041.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy of CHI-5041.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy-of-CHI-5041.jpg"
echo "🧹 Copy of CHI-5652.jpg → Copy-of-CHI-5652.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy of CHI-5652.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy-of-CHI-5652.jpg"
echo "🧹 Copy of CHI-65.jpg → Copy-of-CHI-65.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy of CHI-65.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy-of-CHI-65.jpg"
echo "🧹 Copy of CHI-8649.jpg → Copy-of-CHI-8649.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy of CHI-8649.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy-of-CHI-8649.jpg"
echo "🧹 Copy of CHI-8789.jpg → Copy-of-CHI-8789.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy of CHI-8789.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy-of-CHI-8789.jpg"
echo "🧹 Copy of CHI-9867.jpg → Copy-of-CHI-9867.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy of CHI-9867.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy-of-CHI-9867.jpg"
echo "🧹 Copy of CHI-9872-Website-2.jpg → Copy-of-CHI-9872-Website-2.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy of CHI-9872-Website-2.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy-of-CHI-9872-Website-2.jpg"
echo "🧹 Copy of CHI-Cafe-.jpg → Copy-of-CHI-Cafe.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy of CHI-Cafe-.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy-of-CHI-Cafe.jpg"
echo "🧹 Copy of DSCF1980.jpg → Copy-of-DSCF1980.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy of DSCF1980.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy-of-DSCF1980.jpg"
echo "🧹 Copy of DSCF8938.jpg → Copy-of-DSCF8938.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy of DSCF8938.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy-of-DSCF8938.jpg"
echo "🧹 Copy of Fountain Fairy.jpg → Copy-of-Fountain-Fairy.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy of Fountain Fairy.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy-of-Fountain-Fairy.jpg"
echo "🧹 Copy of Tony_Menias 1.jpg → Copy-of-Tony_Menias-1.jpg"
mv "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy of Tony_Menias 1.jpg" "/home/camo/new/beloveful.com/public/Website beloveful.com/Workshop Photos/Copy-of-Tony_Menias-1.jpg"
echo "🧹 Copy of CHI-0871.jpg → Copy-of-CHI-0871-workshop.jpg"
mv "/home/camo/new/beloveful.com/public/workshop-photos/Copy of CHI-0871.jpg" "/home/camo/new/beloveful.com/public/workshop-photos/Copy-of-CHI-0871-workshop.jpg"
echo "🧹 Copy of CHI-09-19-DSCF5133.jpg → Copy-of-CHI-09-19-DSCF5133-workshop.jpg"
mv "/home/camo/new/beloveful.com/public/workshop-photos/Copy of CHI-09-19-DSCF5133.jpg" "/home/camo/new/beloveful.com/public/workshop-photos/Copy-of-CHI-09-19-DSCF5133-workshop.jpg"
echo "🧹 Copy of CHI-2084-Website-2.jpg → Copy-of-CHI-2084-Website-2-workshop.jpg"
mv "/home/camo/new/beloveful.com/public/workshop-photos/Copy of CHI-2084-Website-2.jpg" "/home/camo/new/beloveful.com/public/workshop-photos/Copy-of-CHI-2084-Website-2-workshop.jpg"
echo "🧹 Copy of CHI-3.jpg → Copy-of-CHI-3-workshop.jpg"
mv "/home/camo/new/beloveful.com/public/workshop-photos/Copy of CHI-3.jpg" "/home/camo/new/beloveful.com/public/workshop-photos/Copy-of-CHI-3-workshop.jpg"
echo "🧹 Copy of CHI-359.jpg → Copy-of-CHI-359-workshop.jpg"
mv "/home/camo/new/beloveful.com/public/workshop-photos/Copy of CHI-359.jpg" "/home/camo/new/beloveful.com/public/workshop-photos/Copy-of-CHI-359-workshop.jpg"
echo "🧹 Copy of CHI-5041.jpg → Copy-of-CHI-5041-workshop.jpg"
mv "/home/camo/new/beloveful.com/public/workshop-photos/Copy of CHI-5041.jpg" "/home/camo/new/beloveful.com/public/workshop-photos/Copy-of-CHI-5041-workshop.jpg"
echo "🧹 Copy of CHI-5652.jpg → Copy-of-CHI-5652-workshop.jpg"
mv "/home/camo/new/beloveful.com/public/workshop-photos/Copy of CHI-5652.jpg" "/home/camo/new/beloveful.com/public/workshop-photos/Copy-of-CHI-5652-workshop.jpg"
echo "🧹 Copy of CHI-65.jpg → Copy-of-CHI-65-workshop.jpg"
mv "/home/camo/new/beloveful.com/public/workshop-photos/Copy of CHI-65.jpg" "/home/camo/new/beloveful.com/public/workshop-photos/Copy-of-CHI-65-workshop.jpg"
echo "🧹 Copy of CHI-8649.jpg → Copy-of-CHI-8649-workshop.jpg"
mv "/home/camo/new/beloveful.com/public/workshop-photos/Copy of CHI-8649.jpg" "/home/camo/new/beloveful.com/public/workshop-photos/Copy-of-CHI-8649-workshop.jpg"
echo "🧹 Copy of CHI-8789.jpg → Copy-of-CHI-8789-workshop.jpg"
mv "/home/camo/new/beloveful.com/public/workshop-photos/Copy of CHI-8789.jpg" "/home/camo/new/beloveful.com/public/workshop-photos/Copy-of-CHI-8789-workshop.jpg"
echo "🧹 Copy of CHI-9867.jpg → Copy-of-CHI-9867-workshop.jpg"
mv "/home/camo/new/beloveful.com/public/workshop-photos/Copy of CHI-9867.jpg" "/home/camo/new/beloveful.com/public/workshop-photos/Copy-of-CHI-9867-workshop.jpg"
echo "🧹 Copy of CHI-9872-Website-2.jpg → Copy-of-CHI-9872-Website-2-workshop.jpg"
mv "/home/camo/new/beloveful.com/public/workshop-photos/Copy of CHI-9872-Website-2.jpg" "/home/camo/new/beloveful.com/public/workshop-photos/Copy-of-CHI-9872-Website-2-workshop.jpg"
echo "🧹 Copy of CHI-Cafe-.jpg → Copy-of-CHI-Cafe-workshop.jpg"
mv "/home/camo/new/beloveful.com/public/workshop-photos/Copy of CHI-Cafe-.jpg" "/home/camo/new/beloveful.com/public/workshop-photos/Copy-of-CHI-Cafe-workshop.jpg"
echo "🧹 Copy of DSCF1980.jpg → Copy-of-DSCF1980-workshop.jpg"
mv "/home/camo/new/beloveful.com/public/workshop-photos/Copy of DSCF1980.jpg" "/home/camo/new/beloveful.com/public/workshop-photos/Copy-of-DSCF1980-workshop.jpg"
echo "🧹 Copy of DSCF8938.jpg → Copy-of-DSCF8938-workshop.jpg"
mv "/home/camo/new/beloveful.com/public/workshop-photos/Copy of DSCF8938.jpg" "/home/camo/new/beloveful.com/public/workshop-photos/Copy-of-DSCF8938-workshop.jpg"
echo "🧹 Copy of Fountain Fairy.jpg → Copy-of-Fountain-Fairy-workshop.jpg"
mv "/home/camo/new/beloveful.com/public/workshop-photos/Copy of Fountain Fairy.jpg" "/home/camo/new/beloveful.com/public/workshop-photos/Copy-of-Fountain-Fairy-workshop.jpg"
echo "🧹 Copy of Tony_Menias 1.jpg → Copy-of-Tony_Menias-1-workshop.jpg"
mv "/home/camo/new/beloveful.com/public/workshop-photos/Copy of Tony_Menias 1.jpg" "/home/camo/new/beloveful.com/public/workshop-photos/Copy-of-Tony_Menias-1-workshop.jpg"

echo "Smart cleanup complete!"
echo "Run npm run portfolio:sync to see improvements"
