import { useMemo } from "react";
import { Navigate, useParams } from "react-router-dom";
import type { Region } from "@/lib/data";

function normalize(input: string): string {
  return input.toLowerCase().replace(/[^a-z]/g, "");
}

const REGION_MAP: Record<string, Region> = {
  africa: "Africa",
  asia: "Asia",
  middleeast: "Middle East",
  southamerica: "South America",
  northamerica: "North America",
  europe: "Europe",
  oceania: "Oceania",
  erasingborders: "Erasing Borders",
  // Additional variations that might be generated by different normalization methods
  europecandinavia: "Europe",
  middleeastnorthafrica: "Middle East",
  erasingbordersproject: "Erasing Borders",
  // More specific variations
  southamericacaibbean: "South America",
  centralamerica: "South America",
  caribbean: "South America",
  eastafrica: "Africa",
  westafrica: "Africa",
  northafrica: "Africa",
  southafrica: "Africa",
  southeastasia: "Asia",
  eastasia: "Asia",
  centralasia: "Asia",
  westasia: "Asia",
  easterneurope: "Europe",
  westerneurope: "Europe",
  northerneurope: "Europe",
  southerneurope: "Europe",
  scandanavia: "Europe",
  scandinavia: "Europe",
  australia: "Oceania",
  newzealand: "Oceania",
};

export default function RegionLanding() {
  const { region } = useParams<{ region: string }>();

  const target = useMemo(() => {
    if (!region) return null;
    
    // Try direct match first
    const key = normalize(region);
    let matchedRegion = REGION_MAP[key];
    
    // If no direct match, try partial matching for complex region names
    if (!matchedRegion) {
      // Check if any region key is contained in the input
      for (const [mapKey, mapValue] of Object.entries(REGION_MAP)) {
        if (key.includes(mapKey)) {
          matchedRegion = mapValue;
          break;
        }
      }
    }
    
    // Final fallback - try matching any word in the region name
    if (!matchedRegion) {
      const words = key.split(/[^a-z]/).filter(word => word.length > 2);
      for (const word of words) {
        const match = REGION_MAP[word];
        if (match) {
          matchedRegion = match;
          break;
        }
      }
    }
    
    return matchedRegion ?? null;
  }, [region]);

  if (!target) {
    return <Navigate to="/portfolio" replace />;
  }
  
  // Redirect to the portfolio page filtered by the resolved region
  const params = new URLSearchParams({ region: target });
  return <Navigate to={`/portfolio?${params.toString()}`} replace />;
}