#!/bin/bash
# Script to create the necessary image directory structure on the server

echo "🔧 Creating required image directory structure..."

# Base path for the public_html directory - using the exact path provided by user
BASE_PATH="/public_html/beloveful.com/public_html"

# Create the main images directory
mkdir -p "$BASE_PATH/images"

# Create region directories
mkdir -p "$BASE_PATH/images/Africa"
mkdir -p "$BASE_PATH/images/Asia"
mkdir -p "$BASE_PATH/images/Central America & Caribbean"
mkdir -p "$BASE_PATH/images/Middle East"
mkdir -p "$BASE_PATH/images/South America"
mkdir -p "$BASE_PATH/images/North America"
mkdir -p "$BASE_PATH/images/Europe & Scandinavia"
mkdir -p "$BASE_PATH/images/Oceania"

# Create country-specific directories with proper case - using "India" as specified by user
mkdir -p "$BASE_PATH/images/Asia/India"
mkdir -p "$BASE_PATH/images/Asia/china"
mkdir -p "$BASE_PATH/images/Asia/hong-kong"
mkdir -p "$BASE_PATH/images/Asia/indonesia"
mkdir -p "$BASE_PATH/images/Asia/japan"
mkdir -p "$BASE_PATH/images/Asia/malaysia"
mkdir -p "$BASE_PATH/images/Asia/new-zealand"
mkdir -p "$BASE_PATH/images/Asia/philippines"
mkdir -p "$BASE_PATH/images/Asia/singapore"
mkdir -p "$BASE_PATH/images/Asia/south-korea"
mkdir -p "$BASE_PATH/images/Asia/taiwan"
mkdir -p "$BASE_PATH/images/Asia/thailand"
mkdir -p "$BASE_PATH/images/Asia/vietnam"
mkdir -p "$BASE_PATH/images/Asia/myanmar"
mkdir -p "$BASE_PATH/images/Asia/nepal"

mkdir -p "$BASE_PATH/images/Europe & Scandinavia/austria"
mkdir -p "$BASE_PATH/images/Europe & Scandinavia/belgium"
mkdir -p "$BASE_PATH/images/Europe & Scandinavia/czech-republic"
mkdir -p "$BASE_PATH/images/Europe & Scandinavia/denmark"
mkdir -p "$BASE_PATH/images/Europe & Scandinavia/finland"
mkdir -p "$BASE_PATH/images/Europe & Scandinavia/france"
mkdir -p "$BASE_PATH/images/Europe & Scandinavia/germany"
mkdir -p "$BASE_PATH/images/Europe & Scandinavia/greece"
mkdir -p "$BASE_PATH/images/Europe & Scandinavia/italy"
mkdir -p "$BASE_PATH/images/Europe & Scandinavia/portugal"
mkdir -p "$BASE_PATH/images/Europe & Scandinavia/spain"
mkdir -p "$BASE_PATH/images/Europe & Scandinavia/uk-ireland"

mkdir -p "$BASE_PATH/images/Africa/egypt"
mkdir -p "$BASE_PATH/images/Africa/ethiopia"
mkdir -p "$BASE_PATH/images/Africa/morocco"
mkdir -p "$BASE_PATH/images/Africa/south-africa"
mkdir -p "$BASE_PATH/images/Africa/namibia"

mkdir -p "$BASE_PATH/images/Middle East/israel-palestine"
mkdir -p "$BASE_PATH/images/Middle East/jordan"

mkdir -p "$BASE_PATH/images/South America/argentina"

mkdir -p "$BASE_PATH/images/North America/chicago"
mkdir -p "$BASE_PATH/images/North America/new-york"

mkdir -p "$BASE_PATH/images/Central America & Caribbean/caribbean"
mkdir -p "$BASE_PATH/images/Central America & Caribbean/cuba"
mkdir -p "$BASE_PATH/images/Central America & Caribbean/mexico"
mkdir -p "$BASE_PATH/images/Central America & Caribbean/puerto-rico"

echo "✅ Directory structure created successfully!"

echo ""
echo "📋 Created the following directory structure:"
echo "   $BASE_PATH/images/"
echo "   ├── Africa/"
echo "   │   ├── egypt/"
echo "   │   ├── ethiopia/"
echo "   │   ├── morocco/"
echo "   │   ├── south-africa/"
echo "   │   └── namibia/"
echo "   ├── Asia/"
echo "   │   ├── India/"  # Using the exact name you provided
echo "   │   ├── china/"
echo "   │   ├── hong-kong/"
echo "   │   ├── indonesia/"
echo "   │   ├── japan/"
echo "   │   ├── malaysia/"
echo "   │   ├── new-zealand/"
echo "   │   ├── philippines/"
echo "   │   ├── singapore/"
echo "   │   ├── south-korea/"
echo "   │   ├── taiwan/"
echo "   │   ├── thailand/"
echo "   │   ├── vietnam/"
echo "   │   ├── myanmar/"
echo "   │   └── nepal/"
echo "   ├── Central America & Caribbean/"
echo "   │   ├── caribbean/"
echo "   │   ├── cuba/"
echo "   │   ├── mexico/"
echo "   │   └── puerto-rico/"
echo "   ├── Europe & Scandinavia/"
echo "   │   ├── austria/"
echo "   │   ├── belgium/"
echo "   │   ├── czech-republic/"
echo "   │   ├── denmark/"
echo "   │   ├── finland/"
echo "   │   ├── france/"
echo "   │   ├── germany/"
echo "   │   ├── greece/"
echo "   │   ├── italy/"
echo "   │   ├── portugal/"
echo "   │   ├── spain/"
echo "   │   └── uk-ireland/"
echo "   ├── Middle East/"
echo "   │   ├── israel-palestine/"
echo "   │   └── jordan/"
echo "   ├── North America/"
echo "   │   ├── chicago/"
echo "   │   └── new-york/"
echo "   ├── South America/"
echo "   │   └── argentina/"
echo "   └── Oceania/"

echo ""
echo "💡 Next steps:"
echo "   1. Upload your image files to the corresponding directories"
echo "   2. Ensure proper file permissions (chmod 644 for images)"
echo "   3. Ensure proper directory permissions (chmod 755 for directories)"
echo "   4. Test a few image URLs to confirm they load correctly"